[Variables]
; Background
FeedreaderBackgroundWidth = 1200
FeedreaderBackgroundHeight = 800
FeedreaderBackgroundColor = FFFFFF30
FeedreaderBackgroundCornerRadius = 10

; Foreground
FeedreaderForegroundOffset = 5
FeedreaderForegroundWidth = 1200
FeedreaderForegroundHeight = 800
FeedreaderForegroundColor = FFFFFFFF
FeedreaderForegroundCornerRadius = 5

; Seperator
FeedReaderNaviContentSeperatorOffset = 300
FeedReaderNaviContentSeperatorWidth = 2
FeedReaderNaviContentSeperatorHeight = (#FeedreaderForegroundHeight#)
FeedReaderNaviContentSeperatorColor = 666666

; Entry
EntryPadding = 33
EntryWidth = 255
EntryHeight = 143

HideEntry1 = [!HideMeter "meterFeedReaderEntryTitle1" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry1" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry1 = [!ShowMeter "meterFeedReaderEntryTitle1" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry1" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry2 = [!HideMeter "meterFeedReaderEntryTitle2" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry2" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry2 = [!ShowMeter "meterFeedReaderEntryTitle2" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry2" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry3 = [!HideMeter "meterFeedReaderEntryTitle3" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry3" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry3 = [!ShowMeter "meterFeedReaderEntryTitle3" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry3" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry4 = [!HideMeter "meterFeedReaderEntryTitle4" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry4" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry4 = [!ShowMeter "meterFeedReaderEntryTitle4" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry4" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry5 = [!HideMeter "meterFeedReaderEntryTitle5" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry5" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry5 = [!ShowMeter "meterFeedReaderEntryTitle5" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry5" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry6 = [!HideMeter "meterFeedReaderEntryTitle6" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry6" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry6 = [!ShowMeter "meterFeedReaderEntryTitle6" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry6" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry7 = [!HideMeter "meterFeedReaderEntryTitle7" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry7" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry7 = [!ShowMeter "meterFeedReaderEntryTitle7" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry7" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry8 = [!HideMeter "meterFeedReaderEntryTitle8" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry8" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry8 = [!ShowMeter "meterFeedReaderEntryTitle8" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry8" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry9 = [!HideMeter "meterFeedReaderEntryTitle9" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry9" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry9 = [!ShowMeter "meterFeedReaderEntryTitle9" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry9" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry10 = [!HideMeter "meterFeedReaderEntryTitle10" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry10" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry10 = [!ShowMeter "meterFeedReaderEntryTitle10" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry10" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry11 = [!HideMeter "meterFeedReaderEntryTitle11" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry11" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry11 = [!ShowMeter "meterFeedReaderEntryTitle11" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry11" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
HideEntry12 = [!HideMeter "meterFeedReaderEntryTitle12" "Minimal\Feedreader"] [!HideMeter "meterFeedReaderEntry12" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]
ShowEntry12 = [!ShowMeter "meterFeedReaderEntryTitle12" "Minimal\Feedreader"] [!ShowMeter "meterFeedReaderEntry12" "Minimal\Feedreader"] [!Redraw "Minimal\Feedreader"]

