[Variables]
FontFamily = Century Gothic

FontSizeSmall = 8
FontSizeMedium = 9
FontSizeBig = 14

FontColorHigh = 255,255,255,255
FontColorLow = 170,170,170,255
FontEffectColor = 0,0,0,20

SkinName = DCal
Scripts = #@#Scripts\#SkinName#\
Images = #@#Images\#SkinName#\
Measures = #@#Measures\#SkinName#\
Meters = #@#Meters\#SkinName#\
Styles = #@#Styles\#SkinName#\
Variables = #@#Variables\#SkinName#\