[Variables]

; Fonts
; ==================================================
FontFamily = Century Gothic

FontSizeSmall = 8
FontSizeMedium = 9
FontSizeBig = 14

FontColorHigh = FFFFFFFF
FontColorLow = AAAAAAFF
FontEffectColor = 00000014

; Bars
; ==================================================
BarColorHigh = 19A2DEFF
BarColorLow = 646464FF

; Seperator
; ==================================================
SeperatorColor = E1E1E123
Transparent = 00000001
OpaqueWhite = FFFFFFFF
OpaqueBlack = 000000FF