[Variables]

; Fonts
; ==================================================
FontFamily = Century Gothic

FontSizeSmall = 8
FontSizeMedium = 9
FontSizeBig = 14

FontColorHigh = FFFFFFFF
FontColorLow = AAAAAAFF
FontEffectColor = 00000014

ColorLowClick = 000000
ColorLowDefault = 222222
ColorLowHover = 444444

ColorMediumClick = 5E5E5E
ColorMediumDefault = 808080
ColorMediumHover = A2A2A2

ColorHighClick = BBBBBB
ColorHighDefault = DDDDDD
ColorHighHover = EEEEEE

; Bars
; ==================================================
BarColorHigh = 19A2DEFF
BarColorLow = 646464FF

; Seperator
; ==================================================
SeperatorColor = E1E1E123
Transparent = 00000001
OpaqueWhite = FFFFFF
OpaqueBlack = 000000