-- {category, identifier, url [, pin]}
-- category: the category the feed is saved under, can be choosen later on from the drop down menu
-- identifier: displayed name of the link to the Feed
-- url: url to the feed to be parsed
-- pin (optional): if true it has higher priority and is as most top as possible
return {
	{'Nachrichten', "Backen macht glücklich", 'http://www.backenmachtgluecklich.de/feed', },
	{'Nachrichten', "Bake a wish", 'http://bake-a-wish-by-carla.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bake at 350", 'http://bakeat350.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bake Break!", 'http://feeds.feedburner.com/bakebreak', },
	{'Nachrichten', "Bake It in a Cake", 'http://bakeitinacake.com/rss', },
	{'Nachrichten', "Bake or Break", 'http://feeds.feedburner.com/BakeOrBreak', },
	{'Nachrichten', "Baked by Rachel", 'http://feeds.feedburner.com/bakedbyrachel', },
	{'Nachrichten', "Baked In", 'http://www.baked-in.com/feed/', },
	{'Nachrichten', "Baked Perfection", 'http://www.bakedperfection.com/feeds/posts/default', },
	{'Nachrichten', "bakerella", 'http://feeds.feedburner.com/Bakerella?format=xml', },
	{'Nachrichten', "Bakergirl", 'http://buddingbaketress.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bakers Royale", 'http://www.bakersroyale.com/feed/atom/', },
	{'Nachrichten', "Bakerydoings", 'http://bakerydoings.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Baking the law's", 'http://bakingthelaw.wordpress.com/feed/ ', },
	{'Nachrichten', "Bakingdom", ' http://feeds.feedburner.com/Bakingdom', },
	{'Nachrichten', "Baltic Maid", 'http://www.balticmaid.com/rss', },
	{'Nachrichten', "bambi backt", 'http://bambi-backt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Barafras Kochlöffel", 'http://barafras-kochloeffel.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Barbara Bakes", 'http://feeds.feedburner.com/BarbaraBakes', },
	{'Nachrichten', "Bashful Bao", 'http://feeds.feedburner.com/bashfulbao/CznU?format=xml', },
	{'Nachrichten', "BBB-Blackiis Bento Blog", 'http://blackiisbentoblog.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Bea's cookbook", 'http://beascookbook.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Beard + Bonnet", 'http://www.beardandbonnet.com/?feed=rss2', },
	{'Nachrichten', "beauté plantureuse ", 'http://beauteplantureuse.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Because You are hungry", 'http://youarehungry.com/feed/', },
	{'Nachrichten', "Bee-inspired", 'http://feeds.feedburner.com/Bee-inspired ', },
	{'Nachrichten', "bellakocht", 'http://bellakocht.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "beneficial bento", 'http://www.beneficial-bento.com/feeds/posts/default', },
	{'Nachrichten', "Bento Amour", 'http://thiscreativedream.wordpress.com/feed/', },
	{'Nachrichten', "Bento Anarchy", 'http://bentoanarchy.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bento Bliss", 'http://feeds.feedburner.com/BentoBliss', },
	{'Nachrichten', "Bento Blog Network", 'http://feeds.feedburner.com/BentoBlogNetwork?format=xml', },
	{'Nachrichten', "Bento Central", 'http://feeds.feedburner.com/BentoCentral', },
	{'Nachrichten', "Bento for Little One", 'http://bentoforlittleone.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bento Lunch Blog", 'http://feeds.feedburner.com/BentoLunchBlog', },
	{'Nachrichten', "Bento Makes Me Happy", 'http://bentomakesmehappy.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bento und mehr", 'http://www.bento-und-mehr.de/feed/', },
	{'Nachrichten', "bento zen", 'http://bentozen.wordpress.com/feed/', },
	{'Nachrichten', "Bento* ??", 'http://rss.exblog.jp/rss/exblog/secdimtem/atom.xml', },
	{'Nachrichten', "Bento, Japan - Daily Kawaii", 'http://dailykawaii.bplaced.net/feed/', },
	{'Nachrichten', "Bento, Monsters", 'http://www.bentomonsters.com/feeds/posts/default', },
	{'Nachrichten', "Bento-Mania", 'http://feeds.feedburner.com/blogspot/MIxvT', },
	{'Nachrichten', "Bentolicious", 'http://www.mybentolicious.com/feeds/posts/default', },
	{'Nachrichten', "BentoLunch", 'http://www.bentolunch.net/feeds/posts/default?alt=rss', },
	{'Nachrichten', "BentOnBetterLunches", 'http://www.bentonbetterlunches.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Bentos on the Bayou", 'http://feeds.feedburner.com/BentosOnTheBayou?format=xml', },
	{'Nachrichten', "Bentown", 'http://veggie-food-love.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Berliner Kürche", 'http://berlinerkueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Berry Lovely", 'http://berry-lovely.blogspot.com/feeds/posts/default ', },
	{'Nachrichten', "Bertie's Bakery", 'http://feeds.feedburner.com/bertiesbakery', },
	{'Nachrichten', "Bespoke-Bride", 'http://www.bespoke-bride.com/rss', },
	{'Nachrichten', "Beyond Kimchee", 'http://feeds.feedburner.com/BeyondKimchee', },
	{'Nachrichten', "Bicil The Baker", 'http://bicilthebaker.wordpress.com/feed/', },
	{'Nachrichten', "Bird On A Cake", 'http://birdonacake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bissen fürs Gewissen", 'http://www.bissenfuersgewissen.com/feeds/posts/default', },
	{'Nachrichten', "Bits of Sunshine", 'http://feeds.feedburner.com/BitsOfSunshine', },
	{'Nachrichten', "Blame it on the bento", 'http://blameitonthebento.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Blessed Homemaker", 'http://feeds.feedburner.com/BlessedHomemaker?format=xml', },
	{'Nachrichten', "bliss bloom", 'http://feeds.feedburner.com/BlissBloomBlog', },
	{'Nachrichten', "Bloglein deck dich", 'http://blogleindeckdich.wordpress.com/feed/', },
	{'Nachrichten', "Blueberry Kitchen", 'http://myblueberrykitchen.com/feed/', },
	{'Nachrichten', "Bobbies Baking Blog", 'http://feeds.feedblitz.com/bobbiesbakingblog/', },
	{'Nachrichten', "Bohnenhase", 'http://bohnenhase.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bonita's Cooking & Bento Wonderland", 'http://bonitofood.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bookatable Blog", 'http://feeds.feedburner.com/bookatableDE?format=xml', },
	{'Nachrichten', "Born in 82", 'http://bornineightytwo.com/feed/', },
	{'Nachrichten', "Boulder Locavore", 'http://feeds.feedburner.com/boulderlocavore', },
	{'Nachrichten', "BraveTart", 'http://bravetart.com/rss/', },
	{'Nachrichten', "Brit + Co.", 'http://www.brit.co/feed/', },
	{'Nachrichten', "Brown Eyed Baker", 'http://feeds.feedburner.com/browneyedbaker/feed', },
	{'Nachrichten', "Brownies for Dinner", 'http://feeds2.feedburner.com/BrowniesForDinner', },
	{'Nachrichten', "BS' in the Kitchen", 'http://bsinthekitchen.com/feed/', },
	{'Nachrichten', "Butter", 'http://butterbaking.wordpress.com/feed/', },
	{'Nachrichten', "Buttercream Blondie", 'http://feeds.feedburner.com/butrcreamblondi', },
	{'Nachrichten', "ButterYum", 'http://butteryum.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Bärenhunger", 'http://baeren-hunger.blogspot.co.at/feeds/posts/default', },
	{'Nachrichten', "C' est moi", 'http://cestmoibeauty.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Café Patita", 'http://cafepatita.net/en/feed/', },
	{'Nachrichten', "Caits Plate", 'http://feeds.feedburner.com/CaitsPlate', },
	{'Nachrichten', "Cake Duchess", 'http://feeds.feedburner.com/cakeduchess', },
	{'Nachrichten', "Cake Invasion!", 'http://cakeinvasion.de/feed/', },
	{'Nachrichten', "Cake Pop My Heart", 'http://cakepopmheart.wordpress.com/feed/', },
	{'Nachrichten', "Cake Pop Princess", 'http://thecakepopprincess.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Cake Whiz", 'http://cakewhiz.com/cakewhiz/syndication.axd ', },
	{'Nachrichten', "cakedecorating", 'http://kelzcakedecoratingtips.wordpress.com/feed/', },
	{'Nachrichten', "CakeJournal", 'http://feeds.feedburner.com/cakejournal?format=xml', },
	{'Nachrichten', "cakelava", 'http://feeds.feedburner.com/blogspot/glZo?format=xml', },
	{'Nachrichten', "CAKES FOR FUN", 'http://cakesforfun.wordpress.com/feed/', },
	{'Nachrichten', "Cakes, Cookies and more", 'http://cakes-cookiesandmore.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Call me cupcake!", 'http://call-me-cupcake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Camille Styles", 'http://camillestyles.com/feed/', },
	{'Nachrichten', "Candy Bar Cupcakes", 'http://candybarcupcakes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Cannella Vita", 'http://feeds.feedburner.com/blogspot/YShsn', },
	{'Nachrichten', "Cannelle et Vanille", 'http://feeds.feedburner.com/blogspot/RKrM', },
	{'Nachrichten', "Casa colorata", 'http://casacolorata.wordpress.com/feed/', },
	{'Nachrichten', "Cause I like food", 'http://feeds.feedburner.com/causeILikeFood', },
	{'Nachrichten', "Charlotte's Diner", 'http://charlottesdiner.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "CharlottenBlog", 'http://feeds.feedburner.com/CharlottenBlog', },
	{'Nachrichten', "Chef Hansen", 'http://www.chefhansen.de/feed/', },
	{'Nachrichten', "chemistryandcloth", 'http://chemistryandcloth.com/feed/', },
	{'Nachrichten', "Cherry on My Sundae", 'http://feeds.feedburner.com/blogspot/dvOJI?format=xml', },
	{'Nachrichten', "Chica and Jo", 'http://feeds.chicaandjo.com/chicaandjo/', },
	{'Nachrichten', "Chili & Tonka", 'http://chilitonka.wordpress.com/feed/', },
	{'Nachrichten', "chocolat bleu", 'http://chocolat-bleu.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Chocolate Chilli Mango", 'http://chocolatechillimango.com/feed/', },
	{'Nachrichten', "Chocolate Covered Katie", 'http://feeds2.feedburner.com/Chocolate-coveredKatie', },
	{'Nachrichten', "Chocolate Moosey", 'http://feeds.feedburner.com/chocolatemooseyblog?format=xml', },
	{'Nachrichten', "Christina macht was!", 'http://christinamachtwas.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Christina's Catchy Cakes", 'http://christinascatchycakes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Clausa Things", 'http://clausathings.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Clean & Scentsible", 'http://feeds.feedburner.com/CleanScentsible', },
	{'Nachrichten', "Cleverly Inspired", 'http://feeds.feedburner.com/Cleverlyinspired', },
	{'Nachrichten', "Colossal", 'http://feeds.feedburner.com/colossal', },
	{'Nachrichten', "Compassionate Cuisine", 'http://compassionatecuisineblog.com/feed/', },
	{'Nachrichten', "Confessions of a Cookbook Queen", 'http://feeds.feedburner.com/ConfessionsOfACookbookQueen', },
	{'Nachrichten', "Confessions", 'http://feeds.feedburner.com/brighteyedbaker/jPDs', },
	{'Nachrichten', "Cooketteria", 'http://cooketteria.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Cookie Ninja", 'http://cookie-ninja.de/feed/', },
	{'Nachrichten', "CookieCrazie", 'http://feeds.feedburner.com/CookieCrazie', },
	{'Nachrichten', "Cookies & Cups", 'http://feeds.feedburner.com/cookiesandcups', },
	{'Nachrichten', "Cookies and Cups", 'http://feeds.feedburner.com/cookiesandcups?format=xml', },
	{'Nachrichten', "Cookin' Canuck", 'http://feeds.feedburner.com/blogspot/hIdj', },
	{'Nachrichten', "Cooking & Fun by Valentina", 'http://feeds.feedburner.com/blogspot/iNkVI', },
	{'Nachrichten', "cooking ala mel", 'http://feeds.feedburner.com/CookingAlaMel?format=xml', },
	{'Nachrichten', "Cooking and Beer", 'http://www.cookingandbeer.com/feed/', },
	{'Nachrichten', "Cooking Classy", 'http://feeds.feedburner.com/blogspot/BfaXW', },
	{'Nachrichten', "Cooking Gallery", 'http://cookinggallery.blogspot.de/feeds/posts/default', },
	{'Nachrichten', "Cooking Melangery", 'http://feeds.feedburner.com/CookingMelangery', },
	{'Nachrichten', "Cooking Tackle", 'http://feeds.feedburner.com/Cookingtackle', },
	{'Nachrichten', "COOKLABO", 'http://feeds.feedburner.com/Cooklabo', },
	{'Nachrichten', "cookmania", 'http://mics-cookmania.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Cooks Joy", 'http://cooksjoy.com/blog/feed', },
	{'Nachrichten', "Cookzilla + Friends", 'http://cookzillaafriends.wordpress.com/feed/', },
	{'Nachrichten', "Copy Paste Love", 'http://feeds.feedburner.com/copypasteloveDasGroeTutorialblog', },
	{'Nachrichten', "Cosycooking", 'http://cosycooking.com/index.php/feed/', },
	{'Nachrichten', "Cotton Candy Stories", 'http://cotton-candy-stories.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "cozy & cuddly", 'http://www.cozy-and-cuddly.de/feed/', },
	{'Nachrichten', "craftbits", 'http://craftbits.com/feed/', },
	{'Nachrichten', "craftgawker", 'http://craftgawker.com/feed/', },
	{'Nachrichten', "Crafttuts+", 'http://feeds.feedburner.com/crafttuts', },
	{'Nachrichten', "Craftzine", 'http://feeds.feedburner.com/craftzine', },
	{'Nachrichten', "Crave. Indulge. Satisfy.", 'http://feeds.feedburner.com/CraveIndulgeSatisfy', },
	{'Nachrichten', "Cream Puffs In Venice", 'http://feeds.feedburner.com/creampuffsinvenice/', },
	{'Nachrichten', "Creative Food", 'http://creative-food.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Creature Comforts", 'http://www.creaturecomfortsblog.com/home/rss.xml', },
	{'Nachrichten', "CRUMB BOSS", 'http://www.crumbboss.com/?feed=rss2', },
	{'Nachrichten', "Crustabakes", 'http://crustabakes.wordpress.com/feed/', },
	{'Nachrichten', "Cucina e Passione", 'http://www.cucinaepassione.de/feed', },
	{'Nachrichten', "Cuisine Paradise", 'http://feeds.feedburner.com/CuisineParadise?format=xml', },
	{'Nachrichten', "Cukrowa Wrózka", 'http://www.cukrowawrozka.pl/feed/', },
	{'Nachrichten', "Culinaria Ungaria", 'http://culinariaungaria.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Culinary Concoctions by Peabody", 'http://feeds.feedburner.com/CulinaryConcoctionsByPeabody', },
	{'Nachrichten', "Cupcake Bakeshop by Chockylit", 'http://cupcakeblog.com/?feed=rss', },
	{'Nachrichten', "Cupcake Liebe", 'http://cupcake-liebe.de/feed/', },
	{'Nachrichten', "Cupcake Project", 'http://feeds.feedburner.com/CupcakeProject', },
	{'Nachrichten', "Cupcakepedia", 'http://cupcakepedia.com/feed/', },
	{'Nachrichten', "Cupcakequeen", 'http://cupcakequeen.de/feed/', },
	{'Nachrichten', "Cupcakes and Berries", 'http://feeds.feedburner.com/blogspot/PKIVxL', },
	{'Nachrichten', "Cupcakes Take The Cake", 'http://cupcakestakethecake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "cupcakesgarden", 'http://www.cupcakesgarden.com/feed/', },
	{'Nachrichten', "cuplovecake", 'http://cuplovecake.de/?feed=rss2', },
	{'Nachrichten', "Cupookie", 'http://cupookie.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Curly Girl Kitchen", 'http://www.curlygirlkitchen.com/feeds/posts/default', },
	{'Nachrichten', "Curvy & Confident", 'http://curvyandconfident.tumblr.com/rss', },
	{'Nachrichten', "Cut Out + Keep", 'http://www.cutoutandkeep.net/projects.atom', },
	{'Nachrichten', "Cute Food For Kids?", 'http://feeds.feedburner.com/CuteFoodForKids', },
	{'Nachrichten', "cuteobento", 'http://feeds.feedburner.com/Cuteobento', },
	{'Nachrichten', "CutestFood", 'http://feeds.feedburner.com/CutestFood', },
	{'Nachrichten', "Czekolada utkane", 'http://www.czekolada-utkane.pl/feeds/posts/default', },
	{'Nachrichten', "Da ist Glitzer in meinem Kuchen!", 'http://glitzerkuchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "dailydelicious", 'http://feeds.feedburner.com/blogspot/dailydelicious', },
	{'Nachrichten', "Danis Zuckerwelt", 'http://zuckerwelt.blogger.de/rss', },
	{'Nachrichten', "Dar Salma", 'http://salmashabbyblog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Das Fräulein mit dem Hund", 'http://dasfraeuleinmitdemhund.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Das Hauptstadtmädchen", 'http://dashauptstadtmaedchen.wordpress.com/feed/', },
	{'Nachrichten', "Das kleine weisse Haus", 'http://das-kleine-weisse-haus.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Das Mädel vom Land", 'http://dasmaedelvomland.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "das tuten der schiffe...", 'http://das-tuten-der-schiffe.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "DaWanda - People and Products with Love", 'http://feeds.feedburner.com/dawanda?format=xml', },
	{'Nachrichten', "de bello culinario", 'http://debelloculinario.com/feed/', },
	{'Nachrichten', "deckschonmaldentisch", 'http://deckschonmaldentisch.wordpress.com/feed/', },
	{'Nachrichten', "Delicious Shots", 'http://deliciousshots.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Delicious Sweet Things", 'http://delicioussweetthings.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "delicious:days", 'http://www.deliciousdays.com/feed/', },
	{'Nachrichten', "deliciously declassified", 'http://feeds.feedburner.com/deliciouslydeclassified', },
	{'Nachrichten', "denna's ideas", 'http://dennasideas.com/feed/', },
	{'Nachrichten', "Der muss haben Sieben Sachen", 'http://dermusshabensiebensachen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Design*Sponge", 'http://feeds.feedburner.com/designspongeonline/njjl', },
	{'Nachrichten', "Desserts by Juliette", 'http://dessertsbyjuliette.com/feed/', },
	{'Nachrichten', "Desserts for Breakfast", 'http://feeds.feedburner.com/dessertsforbreakfast', },
	{'Nachrichten', "DessertStalking", 'http://feeds.feedburner.com/Dessertstalking', },
	{'Nachrichten', "Diamonds for Dessert", 'http://feeds.feedburner.com/diamondsfordessert', },
	{'Nachrichten', "Diane, A Broad", 'http://dianeabroad.com/feed/', },
	{'Nachrichten', "Diary of a Mad Hausfrau", 'http://www.diaryofamadhausfrau.com/feeds/posts/default', },
	{'Nachrichten', "die ja-sagerin", 'http://ja-sagerin.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Die Kleine Küche", 'http://diekleinekueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Die Küchenschabe", 'http://diekuechenschabe.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Die süsse Backstube", 'http://feeds.feedburner.com/DieSuesseBackstube', },
	{'Nachrichten', "Die Umsteiger", 'http://dieumsteiger.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Die vegetarisch – delikate Kochwelt", 'http://kochwelt-blog.de/feed/', },
	{'Nachrichten', "Die Welt der kleinen Dinge", 'http://www.dieweltderkleinendinge.de/feeds/posts/default', },
	{'Nachrichten', "dies´und das und süsse Sachen...", 'http://suesse-hex.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "dieT Taste", 'http://www.diettaste.com/feed', },
	{'Nachrichten', "Digitprop", 'http://digitprop.com/feed/', },
	{'Nachrichten', "dinchensworld", 'http://dinchensworld.wordpress.com/feed/', },
	{'Nachrichten', "Dine and Dish", 'http://dineanddish.net/feed/', },
	{'Nachrichten', "Dinners, Dishes, and Desserts", 'http://feeds.feedburner.com/dinnersdishesanddesserts', },
	{'Nachrichten', "Dodgydumpling", 'http://www.dodgydumpling.com/feeds/posts/default', },
	{'Nachrichten', "Dollhouse Bake Shoppe", 'http://feeds.feedburner.com/dollhousebakeshoppe/XYEJ', },
	{'Nachrichten', "Domestic Fits", 'http://feeds.feedburner.com/domesticfits', },
	{'Nachrichten', "Domestic Superhero", 'domesticsuperhero.com/feed/', },
	{'Nachrichten', "Dough Puncher", 'http://dough-puncher.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Dr Ola's kitchen", 'http://feeds.feedburner.com/blogspot/ZwFRDV', },
	{'Nachrichten', "dramaqueenatwork", 'http://dramaqueenatwork.wordpress.com/feed/', },
	{'Nachrichten', "Draußen nur Kännchen", 'http://dieliebenessy.wordpress.com/feed/', },
	{'Nachrichten', "Dream a Little Bigger", 'http://www.dreamalittlebigger.com/post/rss.xml', },
	{'Nachrichten', "dreierlei liebelei", 'http://feeds.feedburner.com/DreierleiLiebeleiBlogFrSchnes', },
	{'Nachrichten', "DudeFoods.com Food Blog & Reviews", 'http://dudefoods.com/feed/', },
	{'Nachrichten', "Dulce Delight", 'http://www.delightdulce.com/feeds/posts/default', },
	{'Nachrichten', "Dulces bocados", 'http://www.dulcesbocados.com/feeds/posts/default', },
	{'Nachrichten', "Dynamite Cakes", 'http://www.dynamitecakes.de/feed/', },
	{'Nachrichten', "DÜSTERKITSCH", 'http://duesterkitsch.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "eASYbAKED", 'http://easybaked.net/feed/', },
	{'Nachrichten', "eat & think!", 'http://eatandthink.wordpress.com/feed/', },
	{'Nachrichten', "Eat Drink Chic", 'http://feeds.feedburner.com/eatdrinkchic', },
	{'Nachrichten', "Eat Drink Paleo", 'http://eatdrinkpaleo.com.au/feed/', },
	{'Nachrichten', "Eat Me!", 'http://skrebtsova.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "eat sweet. by carla sue", 'http://feeds.feedburner.com/eatsweetycarlasue', },
	{'Nachrichten', "Eat this!", 'http://feeds.feedburner.com/eatthisvegan', },
	{'Nachrichten', "Eating Bird Food", 'http://feeds.feedburner.com/eatingbirdfood/hWrr', },
	{'Nachrichten', "Eating Rules", 'http://feeds.feedburner.com/eatingrules', },
	{'Nachrichten', "Eats Amazing", 'http://feeds.feedburner.com/EatsAmazing', },
	{'Nachrichten', "Eclectic Recipes", 'http://feeds.feedburner.com/Eclectic-Recipes', },
	{'Nachrichten', "Eddy Van Damme", 'http://feeds.feedburner.com/EddyVanDamme', },
	{'Nachrichten', "Effilee", 'http://www.effilee.de/feed', },
	{'Nachrichten', "ein keks für unterwegs", 'http://einkeksfuerunterwegs.wordpress.com/feed/', },
	{'Nachrichten', "Ein klitzeklein(es) Blog", 'http://klitzeklein.wordpress.com/feed/', },
	{'Nachrichten', "Ein Stück vom Glück", 'http://einstueckvomglueck.com/feed/', },
	{'Nachrichten', "Eine Prise Liebe", 'http://jessicarathsack.wordpress.com/feed/', },
	{'Nachrichten', "ELBCUISINE", 'http://www.elbcuisine.de/feed/', },
	{'Nachrichten', "Ellinée", 'http://feeds.feedburner.com/Ellinee', },
	{'Nachrichten', "Elly's Art", 'http://feeds.feedburner.com/EllysArt', },
	{'Nachrichten', "Emily van der Hell", 'http://emily-van-der-hell.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "EmmaBee", 'http://emmabees.wordpress.com/feed/', },
	{'Nachrichten', "En Mi Cocina Hoy", 'http://feeds.feedburner.com/Enmicocinahoy?format=xml', },
	{'Nachrichten', "English Footprints", 'http://www.englishfootprints.com/feeds/posts/default', },
	{'Nachrichten', "EpiCute", 'http://epicute.wordpress.com/feed/', },
	{'Nachrichten', "erdbeerwald", 'http://erdbeerwald.de/feed/', },
	{'Nachrichten', "Erica's Sweet Tooth", 'http://www.ericasweettooth.com/feed', },
	{'Nachrichten', "Erichs kulinarisches Erbe", 'http://feeds.feedburner.com/DdrRezepteampOstdeutscheGerichte-KochenMitVideo-ErichsKulinarischesErbe?format=xml', },
	{'Nachrichten', "Erin's Food Files", 'http://feeds.feedburner.com/ErinsFoodFiles', },
	{'Nachrichten', "Erst mal was essen, dann sehen wir weiter", 'http://erstmalwasessen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Essen aus Engelchens", 'http://engelskueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Essen is fertich!", 'http://essenisfertich.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "eva und ich", 'http://evaundich.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Evan's Kitchen Ramblings", 'http://feeds.feedburner.com/blogspot/bossacafez', },
	{'Nachrichten', "EVERYDAY FLAVOURS", 'http://everydayflavours.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Evil Shenanigans", 'http://feeds.feedburner.com/EvilShenanigansBlog', },
	{'Nachrichten', "eye candy", 'http://feeds.feedburner.com/eyecandyfoodblog', },
	{'Nachrichten', "Fake Food Free", 'http://www.fakefoodfree.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Fat Girl Trapped in a Skinny Body", 'http://feeds.feedburner.com/FatGirlTrappedInASkinnyBody?format=xml', },
	{'Nachrichten', "fearless homemaker", 'http://feeds.feedburner.com/fearlesshomemaker', },
	{'Nachrichten', "feasting at home", 'http://feeds.feedburner.com/FeastingAtHome', },
	{'Nachrichten', "Fee ist mein Name", 'http://www.feeistmeinname.de/feeds/posts/default?alt=rss', },
	{'Nachrichten', "feed me up before you go-go", 'http://feedmeupbeforeyougogo.wordpress.com/feed/', },
	{'Nachrichten', "Feel Wunderbar", 'http://feel-wunderbar.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "feeling a little lunchy", 'http://www.feelingalittlelunchy.com/feeds/posts/default', },
	{'Nachrichten', "feines gemüse", 'http://feines-gemuese.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Feinkostpunks", 'http://feinkostpunks.de/feed/', },
	{'Nachrichten', "feuchtfroehlich", 'http://feuchtfroehlich.wordpress.com/feed/', },
	{'Nachrichten', "Fiber Flux", 'http://feeds.feedburner.com/blogspot/OeRXj', },
	{'Nachrichten', "Finding Vegan", 'http://www.findingvegan.com/rss', },
	{'Nachrichten', "finfint", 'http://finfintfeinerblog.wordpress.com/feed/', },
	{'Nachrichten', "Fit, Fun & Delish!", 'http://www.fit-fun-delish.com/feed', },
	{'Nachrichten', "Five And Spice", 'http://fiveandspice.wordpress.com/feed/', },
	{'Nachrichten', "fleur du poirier", 'http://fleurdupoirier.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Floralilies Zuckerseite", 'http://floralilie.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Flour Arrangements", 'http://feeds.feedburner.com/flourarrangements/feed?format=xml', },
	{'Nachrichten', "FLOUR DE LIS", 'http://flour-de-lis.blogspot.de//feeds/posts/default', },
	{'Nachrichten', "Flowers On My Plate", '"http://feeds.feedburner.com/flowersonmyplate_ger', },
	{'Nachrichten', "Flying Fourchette", 'http://www.flyingfourchette.com/feed/rss/', },
	{'Nachrichten', "food and blood", 'http://foodandblood.wordpress.com/feed/', },
	{'Nachrichten', "Food Doodles", 'http://feeds.feedburner.com/FoodDoodles?format=xml', },
	{'Nachrichten', "Food Nasty", 'http://foodnasty.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Food Vegetarisch", 'http://feeds.feedburner.com/InVegetarischerMission', },
	{'Nachrichten', "Food.People.Want", 'http://www.foodpeoplewant.com/feed/ ', },
	{'Nachrichten', "FoodChomp", 'http://feeds.feedburner.com/FoodChomp', },
	{'Nachrichten', "FoodEpix", 'http://feeds.feedburner.com/feedburner/kWsa', },
	{'Nachrichten', "Foodess", 'http://feeds.feedburner.com/foodess', },
	{'Nachrichten', "foodgawker", 'http://feeds2.feedburner.com/foodgawker', },
	{'Nachrichten', "foodiecrush", 'http://feeds.feedburner.com/foodiecrush', },
	{'Nachrichten', "Foodiggity.com", 'http://feeds.feedburner.com/foodiggity', },
	{'Nachrichten', "Foods for the Soul", 'http://feeds.feedburner.com/foodsforthesoul?format=xml', },
	{'Nachrichten', "foodsandeverything", 'http://foodsandeverything.wordpress.com/feed/', },
	{'Nachrichten', "Fool for Food", 'http://feeds.feedburner.com/rezepte-foolforfood', },
	{'Nachrichten', "foolish fire", 'http://foolishfire.com/feed/', },
	{'Nachrichten', "Fork Knife Swoon", 'http://feeds.feedburner.com/forkknifeswoon', },
	{'Nachrichten', "foxes love lemons", 'http://www.foxeslovelemons.com/feeds/posts/default', },
	{'Nachrichten', "Fraeulein Maier", 'http://fraeuleinmaier.de/feed/', },
	{'Nachrichten', "fraeuleinvomamtskuechenabenteuer", 'http://fraeuleinvomamtskuechenabenteuer.wordpress.com/feed/', },
	{'Nachrichten', "Frau S. verändert die Welt", 'http://frauesveraendertdiewelt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Fried Wontons For You", 'http://friedwontons4u.com/feed/', },
	{'Nachrichten', "Frl. Moonstruck kocht!", 'http://www.frl-moonstruck-kocht.de/feeds/posts/default', },
	{'Nachrichten', "Frollein Leni", 'http://www.frollein-leni.com/feeds/posts/default', },
	{'Nachrichten', "From My Lemony Kitchen", 'http://feeds.feedburner.com/FromMyLemonyKitchen?format=xml', },
	{'Nachrichten', "From Scratch", 'http://copykatcook.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "From Veggie to Vegan", 'http://petzig.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "froschgrün", 'http://feeds.feedburner.com/froschgruen', },
	{'Nachrichten', "Fräulein Cupcake", 'http://fraeuleincupcake.wordpress.com/feed/', },
	{'Nachrichten', "fräulein glücklich", 'http://fraeulein-gluecklich.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Fräulein Sorgenfrei", 'http://www.fraeulein-sorgenfrei.de/?feed=rss2', },
	{'Nachrichten', "Fräulein Text", 'http://fraeuleintext.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Full-thyme Student", 'http://feeds.feedburner.com/fullthymestudent?format=xml', },
	{'Nachrichten', "Funkytime", 'http://fun.kyti.me/index.php/feed/', },
	{'Nachrichten', "Fête à Fête", 'http://fete-a-fete.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Garden Therapy", 'http://feeds.feedburner.com/GardenTherapy', },
	{'Nachrichten', "Gaumenthrill", 'http://gaumenthrill.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Geek Art Gallery", 'http://feeds.feedburner.com/GeekArtGallery ', },
	{'Nachrichten', "Gimme Some Style", 'http://feeds.feedburner.com/gimmesomestyle', },
	{'Nachrichten', "giroVegando in cucina", 'http://girovegandoincucina.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "glitzergruen", 'http://glitzergruen.wordpress.com/feed/', },
	{'Nachrichten', "Glomery Lane", 'http://feeds.feedburner.com/GlomeryLane', },
	{'Nachrichten', "Glorious Treats", 'http://feeds.feedburner.com/GloriousTreats', },
	{'Nachrichten', "glückSEEligkeit", 'http://glueckseeligkeit.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Go Make Me", 'http://feeds.feedburner.com/typepad/jiNL', },
	{'Nachrichten', "Go Origami!", 'http://feeds.feedburner.com/goorigami', },
	{'Nachrichten', "Golubka", 'http://g0lubka.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Good Thymes and Good Food", 'http://feeds.feedburner.com/goodthymesandgoodfood/FGcL?format=xml', },
	{'Nachrichten', "Gourmande in the Kitchen", 'http://feeds.feedburner.com/gourmandeinthekitchen/rUSK', },
	{'Nachrichten', "Gourmandises végétariennes", 'http://gourmandisesvegetariennes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "GourmetGuerilla", 'http://www.gourmetguerilla.de/?feed=rss2', },
	{'Nachrichten', "grain de sel - salzkorn", 'http://salzkorn.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Greenway36", 'http://greenway36food.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Grilled Cheese Social", 'http://feeds.feedburner.com/GrilledCheeseSocial', },
	{'Nachrichten', "Gute Laune mit Schokolade", 'http://feeds.feedburner.com/GuteLauneMitSchokolade', },
	{'Nachrichten', "Gwen's Kitchen Creations", 'http://gwenskitchencreations.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Hail Seitan!", 'http://churchofseitan.wordpress.com/feed/', },
	{'Nachrichten', "Hair Romance", 'http://feeds.feedburner.com/hairromance', },
	{'Nachrichten', "Half Baked Harvest", 'http://www.halfbakedharvest.com/feed/', },
	{'Nachrichten', "Half Baked", 'http://feeds2.feedburner.com/HalfBakedTheCakeBlog', },
	{'Nachrichten', "Handle the Heat", 'http://feeds.feedburner.com/HandleTheHeat?format=xml', },
	{'Nachrichten', "Handmade Charlotte", 'http://feeds.feedburner.com/handmadecharlotte', },
	{'Nachrichten', "Haniela's", 'http://feeds.feedburner.com/Hanielas', },
	{'Nachrichten', "happiness is a warm bun", 'http://bakermel.wordpress.com/feed/', },
	{'Nachrichten', "Happy Little Bento", 'http://feeds.feedburner.com/HappyLittleBento', },
	{'Nachrichten', "Happy Pretty Things", 'http://feeds.feedburner.com/happyprettylittlethings', },
	{'Nachrichten', "Happy vegan girls", 'http://vegan-girls.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Harissaliebe", 'http://harissaliebe.wordpress.com/feed/', },
	{'Nachrichten', "Harr Cooking", 'shttp://harrcooking.tumblr.com/rss', },
	{'Nachrichten', "Hawaii Kawaii Blog", 'http://feeds.feedburner.com/hawaiikawaii', },
	{'Nachrichten', "Healthy Aperture", 'http://www.healthyaperture.com/feed', },
	{'Nachrichten', "Healthy. Happy. Life.", 'http://feeds.feedburner.com/KathysBlogHealthyHappyLife?format=xml', },
	{'Nachrichten', "Heather Bullard", 'http://feeds.feedburner.com/PresentpastCollection', },
	{'Nachrichten', "Heather's French Press", 'http://www.heathersfrenchpress.com/feed', },
	{'Nachrichten', "Heavenly Cake Pops ", 'http://heavenlycakepops.com/feed/', },
	{'Nachrichten', "Heidewitzka!", 'http://heide-witzka.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Heikes Blog", 'http://heike.essenvonau.de/feed/', },
	{'Nachrichten', "Hej Holunder!", 'http://hejholunder.wordpress.com/feed/', },
	{'Nachrichten', "Helen's Road to Wellville", 'http://helensroadtowellville.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Hello Bento Projekt", 'http://hello-bento.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Hello Home Shoppe", 'http://feeds.feedburner.com/HelloHomeShoppe', },
	{'Nachrichten', "hello hydrangea", 'http://feeds.feedburner.com/HelloHydrangea', },
	{'Nachrichten', "Hello Kitty Hell", 'http://feeds.feedburner.com/HelloKittyHell', },
	{'Nachrichten', "Helma's Kitchen", 'http://helmaskitchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "heo yeah yum", 'http://heoyeahyum.com/feed/', },
	{'Nachrichten', "herzelieb", 'http://feeds.feedburner.com/Herzelieb?format=xml', },
	{'Nachrichten', "Herzfutter", 'http://www.herzfutter.net/feeds/posts/default', },
	{'Nachrichten', "HEY LOOK", 'http://feeds.feedburner.com/heylook_fi', },
	{'Nachrichten', "Hey, Gorgeous", 'http://www.heygorg.com/feed', },
	{'Nachrichten', "HiConsumption", 'http://feeds.feedburner.com/freshcommedia/HiConsumption', },
	{'Nachrichten', "hidden kitchen", 'http://www.hidden-kitchen.de/feed/', },
	{'Nachrichten', "HighFoodality", 'http://feeds.feedburner.com/highfoodality', },
	{'Nachrichten', "Himbeerprinzesschen", 'http://himbeerprinzesschen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Himmlische Süßigkeiten", 'http://himmlischesuessigkeiten.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "hinzhej", 'http://hinzhej.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Hoetus Poetus", 'http://hoetuspoetus.wordpress.com/feed/', },
	{'Nachrichten', "Home Heart Craft", 'http://www.homeheartcraft.com/blog.rss', },
	{'Nachrichten', "Home is where the Törtchen is", 'http://mytoertchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Homemade deliciousness", 'http://homemadedeliciousness.wordpress.com/feed/', },
	{'Nachrichten', "homemade treats", 'http://sandras-homemadetreats.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "honey & jam", 'http://feeds.feedburner.com/honeyandjam/kutd', },
	{'Nachrichten', "honigkuchenpferd", 'http://www.honigkuchenpferd.com/rss.xml', },
	{'Nachrichten', "Honigsüß", 'http://honigsuess.wordpress.com/feed/', },
	{'Nachrichten', "hoopla palooza", 'http://feeds.feedburner.com/HooplaPalooza?format=xml', },
	{'Nachrichten', "Hoosier Homemade", 'http://hoosierhomemade.com/feed/', },
	{'Nachrichten', "Hostess with the Mostess", 'http://feeds.feedburner.com/hostessblog', },
	{'Nachrichten', "Hot Pot Cooking", 'http://feeds.feedburner.com/blogspot/hotpotmeal', },
	{'Nachrichten', "How About Orange", 'http://feeds.feedburner.com/HowAboutOrange', },
	{'Nachrichten', "How Sweet It Is", 'http://feeds.feedburner.com/howsweeteats/smSp', },
	{'Nachrichten', "HowToCookThat", 'http://feeds.feedburner.com/HowToCookThat', },
	{'Nachrichten', "Hummingbird High", 'http://feeds.feedburner.com/HummingbirdOnHigh', },
	{'Nachrichten', "Hungry at Midnight", 'http://hungryatmidnight.com/feed/', },
	{'Nachrichten', "hungry brownie", 'http://www.hungrybrownie.com/feed/', },
	{'Nachrichten', "Hungry Happenings", 'http://feeds.feedburner.com/hungryhappenings/naJY', },
	{'Nachrichten', "hungry rabbit", 'http://feeds.feedburner.com/hungryrabbit', },
	{'Nachrichten', "HungryHuy", 'http://feeds.feedburner.com/HungryHuy', },
	{'Nachrichten', "Hyperbole and a Half", 'http://feeds.feedburner.com/Hyperbole-and-a-half?format=xml', },
	{'Nachrichten', "Hüttenhilfe", 'http://feeds.feedburner.com/huettenhilfe', },
	{'Nachrichten', "i am baker", 'http://feeds.feedburner.com/typepad/xEQi', },
	{'Nachrichten', "i heart baking!", 'http://i-heart-baking.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "i heart eating", 'http://www.ihearteating.com/feed/', },
	{'Nachrichten', "I Heart Nap Time", 'http://www.iheartnaptime.net/feed/', },
	{'Nachrichten', "I Sugar Coat It!", 'http://www.isugarcoatit.com/feeds/posts/default', },
	{'Nachrichten', "Ich bin dann mal kurz in der Küche", 'http://mal-kurz-in-der-kueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "ICH und BENTO", 'http://ichundbento.wordpress.com/feed/', },
	{'Nachrichten', "Ichigo Shortcake", 'http://feeds.feedburner.com/IchigoShortcake', },
	{'Nachrichten', "If in doubt, bake a cake!", 'http://happy-meal-time.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "IFeelCook", 'http://ifeelcook.es/feed/', },
	{'Nachrichten', "iFOODreal", 'http://www.ifoodreal.com/feed/', },
	{'Nachrichten', "In Pursuit of More", 'http://inpursuitofmore.com/feed/', },
	{'Nachrichten', "IndianSimmer", 'http://feeds.feedburner.com/indiansimmer', },
	{'Nachrichten', "Inquiring Chef", 'http://feeds.feedburner.com/InquiringChef?format=xml', },
	{'Nachrichten', "Inside BruCrew Life", 'http://feeds.feedburner.com/InsideBrucrewLife', },
	{'Nachrichten', "Inspired Edibles", 'Inspired Edibleshttp://feeds.feedburner.com/trinitynutrition?format=xml', },
	{'Nachrichten', "IRENA & dots", 'http://irenasdots.wordpress.com/feed/', },
	{'Nachrichten', "It Bakes Me Happy", 'http://www.itbakesmehappy.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Itadakimasu - Guten Appetit", 'http://itadakimasu-gutenappetit.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Italian Chips", 'http://italianchips.com/feed/', },
	{'Nachrichten', "Japan-Infos", 'http://japan-infos.de/feed/rss', },
	{'Nachrichten', "JavaCupcake", 'http://javacupcake.com/feed/', },
	{'Nachrichten', "Je suis alimentageuse", 'http://alimentageuse.com/feed/', },
	{'Nachrichten', "Jelly Shot Test Kitchen", 'http://feeds.feedburner.com/JellyShotTestKitchen', },
	{'Nachrichten', "Jelly Toast", 'http://feeds.feedburner.com/JellyToast', },
	{'Nachrichten', "Jen's Favorite Cookies", 'http://www.jensfavoritecookies.com/feed/', },
	{'Nachrichten', "Jennys Backwelt", 'http://jennys-backwelt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Jessicakes", 'http://jessicakesblog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Jessie schmeckts!", 'http://jessieschmeckts.wordpress.com/feed/', },
	{'Nachrichten', "Jeyashri's Kitchen", 'http://feeds.feedburner.com/jeyashriskitchen/JUSO', },
	{'Nachrichten', "joliemauli", 'http://joliemauli.wordpress.com/feed/', },
	{'Nachrichten', "jothetartqueen", 'http://jothetartqueen.wordpress.com/feed/', },
	{'Nachrichten', "Joy of Jello", 'http://feeds.feedburner.com/JoyOfJello', },
	{'Nachrichten', "Joy the Baker", 'http://joythebaker.com/feed/', },
	{'Nachrichten', "JuliesMagazine", 'http://magazineofjulie.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "junifaden", 'http://junifaden.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Juniper Cakery", 'http://junipercakery.co.uk/blog/feed/', },
	{'Nachrichten', "Just as Delish", 'http://feeds.feedburner.com/justasdelish', },
	{'Nachrichten', "Just Bento", 'http://feeds.feedburner.com/justbento', },
	{'Nachrichten', "Just Hungry", 'http://feeds.feedburner.com/justhungry', },
	{'Nachrichten', "Just My Delicious", 'http://www.justmydelicious.com/feeds/posts/default', },
	{'Nachrichten', "Just One Cookbook", 'http://justonecookbook.com/blog/feed/', },
	{'Nachrichten', "justJENN", 'http://feeds.feedburner.com/justjennrecipes/rMLz?format=xml', },
	{'Nachrichten', "K A W A I I - B L O G ", 'http://www.kawaii-blog.org/feed/', },
	{'Nachrichten', "K.abc", 'http://kabcphotography.wordpress.com/feed/', },
	{'Nachrichten', "Kailley's Kitchen", 'http://www.kailleyskitchen.com/feed/', },
	{'Nachrichten', "Kalinka's Kitchen", 'http://kalinkaskitchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "kandeej", 'http://www.kandeej.com/feeds/posts/default', },
	{'Nachrichten', "Karens-Backwahn", 'http://feeds.feedburner.com/blogspot/dSOEE', },
	{'Nachrichten', "Karenwee's Bento Diary", 'http://kwbentodiary.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Katha-kocht!", 'http://katha-kocht.com/feed/', },
	{'Nachrichten', "kathastrophal", 'http://kathastrophal.de/feed', },
	{'Nachrichten', "Kathls Backstum", 'http://kathlsbackstum.wordpress.com/feed/', },
	{'Nachrichten', "Katiecakes", 'http://feeds.feedburner.com/iheartkatiecakes/HopT', },
	{'Nachrichten', "Katja's Küche", 'http://katjaskueche.wordpress.com/feed/', },
	{'Nachrichten', "Kawaii Foods", 'http://feeds.feedburner.com/KawaiiFoods', },
	{'Nachrichten', "Kazuo", 'http://mari-to-kazuo.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "KC Bakes", 'http://mykcbakes.wordpress.com/feed/', },
	{'Nachrichten', "Keep Calm And Relax", 'http://keepcalm-andrelax.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Keepin' It Kind", 'http://keepinitkind.com/feed/', },
	{'Nachrichten', "kelly bakes", 'http://feeds.feedburner.com/kellybakes/UpmI', },
	{'Nachrichten', "Kirbie's Cravings", 'http://feeds.feedburner.com/KirbieCravings?format=xml', },
	{'Nachrichten', "Kirschkuchen", 'http://erdbeerkirsch.blogspot.de/feeds/posts/default', },
	{'Nachrichten', "Kitchen Bloody Kitchen", 'http://feeds.feedburner.com/kitchenbloodykitchen', },
	{'Nachrichten', "Kitchen Konfidence", 'http://feeds.feedburner.com/KitchenKonfidence?format=xml', },
	{'Nachrichten', "KITCHEN TESTED", 'http://feeds.feedburner.com/kitchen-tested/kt-blog', },
	{'Nachrichten', "Kitchen to Nirvana", 'http://feeds.feedburner.com/KitchenToNirvana', },
	{'Nachrichten', "Kitchen Vignettes by Aubergine", 'http://kitchenvignettes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Kleeundkleiber", 'http://kleeundkleiber.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Kleine Tortenfee", 'http://kleine-tortenfee.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Kleiner Kuriositätenladen", 'http://www.kuriositaetenladen.com/feeds/posts/default', },
	{'Nachrichten', "Kleines Freudenhaus", 'http://jules-kleines-freudenhaus.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Knitty baker", 'http://feeds.feedburner.com/KnittyBaker?format=xml', },
	{'Nachrichten', "Kochen für Schlampen", 'http://kochschlampe.com/feed/', },
	{'Nachrichten', "Kochen und genießen mit Winnegirl", 'http://feeds.feedburner.com/winnegirl', },
	{'Nachrichten', "Kochfieber", 'http://kochfieber.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Kochfrosch", 'http://kochfrosch.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "kreativfieber", 'http://kreativfieber.de/feed/', },
	{'Nachrichten', "Krissy's Creations", 'http://www.krissys-creations.com/feeds/posts/default', },
	{'Nachrichten', "Kuchenschlacht", 'http://mikebravo.dyndns.org/wordpress/?feed=rss2', },
	{'Nachrichten', "Kuechenchaotin", 'http://feeds.feedburner.com/Kuechenchaotin', },
	{'Nachrichten', "kunterbuntweissblau", 'http://kunterbuntweissblau.wordpress.com/feed/', },
	{'Nachrichten', "Kurze´s Köstlichkeiten", 'http://feeds.feedburner.com/kurzeskoestlichkeiten?format=xml', },
	{'Nachrichten', "KÜCHENkataSTROPHEN", 'http://feeds.feedburner.com/Kchenkatastrophen', },
	{'Nachrichten', "Küchentanz", '"http://feeds2.feedburner.com/kuechentanzEline', },
	{'Nachrichten', "La Cucharina Mágica", 'http://feeds.feedburner.com/LaCucharinaMgica', },
	{'Nachrichten', "la petite cuisine", 'http://la-petite-cuisine.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "La Receta de la Felicidad", 'http://www.larecetadelafelicidad.com/en/feed', },
	{'Nachrichten', "lab@56", 'http://feeds.feedburner.com/lab56', },
	{'Nachrichten', "lachenlebenlieben", 'http://lachenlebenlieben.wordpress.com/feed/', },
	{'Nachrichten', "Lady and Pups", 'http://www.ladyandpups.com/feed/', },
	{'Nachrichten', "lamiacucina", 'http://lamiacucina.wordpress.com/feed/', },
	{'Nachrichten', "Lana Red Studio", 'http://lanared.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "larissaswelt", 'http://larissaswelt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Last Ingredient", 'http://www.lastingredient.com/feed/', },
	{'Nachrichten', "Laubfresser", 'http://www.laubfresser.de/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Lavender and Lovage", 'http://feeds.feedburner.com/LavenderAndLovage', },
	{'Nachrichten', "Lavender's Blue Designs", 'http://feeds.feedburner.com/LavendersBlueDesigns', },
	{'Nachrichten', "Le bon vivant", 'http://lebonvivant.net/feed/', },
	{'Nachrichten', "Leanne bakes", 'http://www.leannebakes.com/feeds/posts/default', },
	{'Nachrichten', "Lebensszenen", 'http://www.sscenesdelavie.blogspot.de/feeds/posts/default', },
	{'Nachrichten', "Lecker Bentos und mehr", 'http://lecker-bentos-und-mehr.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "lecker macht laune", 'http://www.leckermachtlaune.de/?feed=rss2', },
	{'Nachrichten', "LECKER", 'http://besonders.lecker.de/rss/tagesrezept.php', },
	{'Nachrichten', "leckertipps", 'http://www.leckertipps.de/rss/blog', },
	{'Nachrichten', "Lemon Sugar", 'http://feeds.feedburner.com/lemon-sugar/oFwp?format=xml', },
	{'Nachrichten', "Les Tissus Colbert", 'http://lestissuscolbert.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Let the Baking Begin!", 'http://letthebakingbeginblog.com/feed/', },
	{'Nachrichten', "Let them eat Cupcakes", 'http://naschcupcakes.blogspot.de/feeds/posts/default', },
	{'Nachrichten', "Letizias Gaumenfreuden", 'http://www.waskochen.ch/letizias-gaumenfreuden/feed/', },
	{'Nachrichten', "Lets Go Sunning", 'http://feeds.feedburner.com/letsgosunning', },
	{'Nachrichten', "Liebe geht durch den Magen", 'http://kreativeskuechenchaos.wordpress.com/feed/', },
	{'Nachrichten', "Liebe im Bauch", 'http://liebeimbauch.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Liebelei und Bastelei", 'http://liebeleiundbastelei.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Life Love Food", 'http://feeds.feedburner.com/blogspot/qpccg', },
	{'Nachrichten', "Life made Sweeter", 'http://feeds.feedburner.com/lifemadesweeter/FlvL?format=xml ', },
	{'Nachrichten', "like a piece of new york cheesecake", 'http://ny-cheesecake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Lil' Luna", 'http://feeds.feedburner.com/lilluna/isXQ', },
	{'Nachrichten', "LilaLoa", 'http://www.lilaloa.com/feeds/posts/default', },
	{'Nachrichten', "Limeshot Logo Design & Branding Sydney", 'http://limeshot.com/feed', },
	{'Nachrichten', "Lingonberry Jam", 'http://lingonberryjam.wordpress.com/feed/', },
	{'Nachrichten', "Lisa Storms", 'http://lisastorms.typepad.com/lisa-storms/atom.xml', },
	{'Nachrichten', "Lisa´s Kochfieber", 'http://feeds.feedburner.com/LisasKochfieber', },
	{'Nachrichten', "Lisbeth`s Cupcakes & Cookies", 'http://lisbethscupcake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Little Bitty Bakes", 'http://feeds.feedburner.com/LittleBittyBakes', },
	{'Nachrichten', "Little Delights Cakes", 'http://littledelightscakes.com/feed/', },
	{'Nachrichten', "Little Miss Onigiri", 'http://littlemissonigiri.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "live life deeply-now", 'http://livelifedeeply-now.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Living Healthy With Chocolate", 'http://livinghealthywithchocolate.com/feed/', },
	{'Nachrichten', "Living Tastefully", 'http://livingtastefully.weebly.com/2/feed', },
	{'Nachrichten', "Love Cook Eat", 'http://lovecookeat.com/feed/', },
	{'Nachrichten', "Love Raw", 'http://loveraw.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "love.life.eat", 'http://lovelifeeat.com/feed/', },
	{'Nachrichten', "Lovely Indeed", 'http://feeds.feedburner.com/lovelyindeed', },
	{'Nachrichten', "lovingvegan", 'http://lovingvegan.wordpress.com/feed/', },
	{'Nachrichten', "Lulu the Baker", 'http://luluthebaker.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Lulu's Sweet Secrets", 'http://lulussweetsecrets.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "lululu at home", 'http://lululuathome.com/feed', },
	{'Nachrichten', "lunasphilosophy", 'http://lunasphilosophy.wordpress.com/feed/', },
	{'Nachrichten', "Lunch For One", 'http://feeds.feedburner.com/wordpress/IzLC', },
	{'Nachrichten', "Lydia Bakes", 'http://www.lydiabakes.com/feeds/posts/default', },
	{'Nachrichten', "Lykkelig", 'http://meinlykkelig.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Madame Gateau", 'http://www.barbaragateau.com/feeds/posts/default', },
	{'Nachrichten', "maedchenkantine", 'http://maedchenkantine.wordpress.com/feed/', },
	{'Nachrichten', "maedchenmitherz", 'maedchenmitherz.wordpress.com/rss', },
	{'Nachrichten', "Magdalena", 'http://www.torten.org/feed/', },
	{'Nachrichten', "MagicallyDelicious", 'http://magicallydelicious.com/feed/', },
	{'Nachrichten', "magnoliaelectric", 'http://www.magnoliaelectric.net/feeds/posts/default', },
	{'Nachrichten', "Make Life Lovely", 'http://make-life-lovely.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Make.Bake.Celebrate", 'http://makebakecelebrate.com/feed/', },
	{'Nachrichten', "Makeup your Jangsara", 'http://feeds.feedburner.com/blogspot/YxfBu', },
	{'Nachrichten', "Makoodle", 'http://feeds.feedburner.com/Makoodle', },
	{'Nachrichten', "Mampfnudel", 'http://www.mampfnudel.de/feed/', },
	{'Nachrichten', "MAN BAKES CAKE", 'http://manbakescake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mandarin Peach", 'http://feeds.feedburner.com/MandarinPeach', },
	{'Nachrichten', "Manila Spoon", 'http://www.manilaspoon.com/feeds/posts/default', },
	{'Nachrichten', "Maple Spice", 'http://www.maplespice.com/feeds/posts/default', },
	{'Nachrichten', "Mara's", 'http://feeds.feedburner.com/Maras?format=xml', },
	{'Nachrichten', "Maras Wunderland", 'http://www.maraswunderland.de/feed/', },
	{'Nachrichten', "Maria mag Törtchen", 'http://www.mariamagtoertchen.de/feed/', },
	{'Nachrichten', "Marylicious", 'http://www.marylicious.de/feed/', },
	{'Nachrichten', "MehlspeisDirndl*", 'http://mehlspeisdirndl.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "mein i tüpfelchen", 'http://meinituepfelchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Meine Küche ist mein Königreich", 'http://backparadies.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Meine Küchenschlacht", 'http://raunbowsugersprinkles.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "melimelo", 'http://feeds.feedburner.com/blogspot/heAfx', },
	{'Nachrichten', "Melis bunte Studentenküche", 'http://melis-bunte-studentenkueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "mellimille", 'http://mellimille.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mestolo", 'http://mestolo.com/feed/', },
	{'Nachrichten', "Mias Tortenwelt", 'http://www.miastortenwelt.de/feed/', },
	{'Nachrichten', "Mighty Delighty", 'http://feeds.feedburner.com/MightyDelighty', },
	{'Nachrichten', "Milk & Cereal", 'http://feeds.feedburner.com/MilkCereal?format=xml', },
	{'Nachrichten', "Milk and Honey", 'http://milk-and.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mimi's Fairy Cakes", 'http://mimis-fairycakes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Minebento", 'http://minebento.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mini Matriarchin", 'http://minimatriarchin.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mini-eco", 'http://feeds.feedburner.com/minieco', },
	{'Nachrichten', "Minted Strawberry", 'http://feeds.feedburner.com/MintedStrawberry', },
	{'Nachrichten', "Miri's Kitchen", 'http://miris-kitchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Miris Jahrbuch", 'http://mirisjahrbuch.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Misato Neko", 'http://misatoneko.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Miss Blueberrymuffin's kitchen", 'http://missblueberrymuffin.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "MISS CANDIQUIK", 'http://blog.candiquik.com/?feed=rss2', },
	{'Nachrichten', "miss crosstitch's Blog", 'http://misscrossstitch.wordpress.com/feed/', },
	{'Nachrichten', "Miss Golosinas", 'http://missgolosinas.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Miss Ju", 'http://www.miss-ju.at/feeds/posts/default', },
	{'Nachrichten', "Mit Zucker, Salz & Bauchgefühl", 'http://zucker-und-salz.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "moey's kitchen", 'http://moeyskitchen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Moje Wypieki", 'http://www.mojewypieki.com/rss/posty', },
	{'Nachrichten', "Molly Moo", 'http://mollymoo.ie/feed/', },
	{'Nachrichten', "Mom's Love In Bento", 'http://momsloveinbento.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "momsbyheart", 'http://feeds2.feedburner.com/blogspot/krGS', },
	{'Nachrichten', "MoreDesignPlease", 'http://www.moredesignplease.com/moredesignplease/rss.xml', },
	{'Nachrichten', "morgenrosa", 'http://morgenrosa.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mothering Corner", 'http://motheringcorner.com/feed/', },
	{'Nachrichten', "Mowielicious", 'http://feeds.feedburner.com/Mowielicious', },
	{'Nachrichten', "Mrs Happy Homemaker", 'http://feeds.feedburner.com/MrsHappyHomemaker', },
	{'Nachrichten', "mrs. mandel", 'http://mrsmandel.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Muffin Queen", 'http://muffin-queen.jimdo.com/rss/blog', },
	{'Nachrichten', "Muffin Queen", 'http://muffinqueenblog.wordpress.com/feed/', },
	{'Nachrichten', "Muffinmonster", 'http://www.muffinmonster.de/feed/', },
	{'Nachrichten', "mug.veg", 'http://mucveg.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Munchkin Munchies", 'http://feeds.feedburner.com/MunchkinMunchies', },
	{'Nachrichten', "My Backyard Monsters", 'http://mybackyardmonsters.tumblr.com/rss', },
	{'Nachrichten', "My Baking Addiction", 'http://feeds.feedblitz.com/mybakingaddiction&x=1', },
	{'Nachrichten', "my cooking love affair", 'http://mycookingloveaffair.de/feed/', },
	{'Nachrichten', "My Easy Gourmet", 'http://myeasygourmet.net/feed/', },
	{'Nachrichten', "My Happy Dessert", 'http://www.myhappydessert.com/feed/', },
	{'Nachrichten', "My Little Fabric", 'http://www.mylittlefabric.com/feed/', },
	{'Nachrichten', "my little japanese world", 'http://my-little-japanese-world.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "My New Roots", 'http://feeds.feedburner.com/My-New-Roots', },
	{'Nachrichten', "My Own Ideas — My Own Ideas", 'http://www.myownlabels.com/blog/rss', },
	{'Nachrichten', "My pans and pots", 'http://feeds.feedburner.com/MyPansAndPots', },
	{'Nachrichten', "My So Called Crafty Life", 'http://www.mysocalledcraftylife.com/feed/', },
	{'Nachrichten', "my utensil crock", 'http://myutensilcrock.com/feed/', },
	{'Nachrichten', "My World", 'http://ronja-myworld.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Mädchen mit Herz", 'http://craftvoll.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "N i c e s t    T h i n g s", 'http://www.nicestthings.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Nachgekocht", 'http://nachkochen.wordpress.com/feed/', },
	{'Nachrichten', "Natural Sweet Recipes", 'http://www.naturalsweetrecipes.com/feed/', },
	{'Nachrichten', "nekoblog", 'http://www.nekoblog.ch/feed', },
	{'Nachrichten', "New Kitch On The Blog", 'http://new-kitch-on-the-blog.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "nici is going crazy", 'http://nici.stueben.net/feed/', },
	{'Nachrichten', "Nicky&Max", 'http://nickyandmax.com/feed/', },
	{'Nachrichten', "nikesherztanzt", 'http://nikesherztanzt.wordpress.com/feed/', },
	{'Nachrichten', "Nimmersatt", 'http://nimmer-satt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Ninas kleiner Food-Blog", 'http://feeds.feedburner.com/NinasKleinerFood-blog', },
	{'Nachrichten', "niner bakes", 'http://feeds.feedburner.com/ninerbakes', },
	{'Nachrichten', "No Kitchen For Old Men", 'http://nokitchenforoldmen.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "no. 2 pencil", 'http://www.number-2-pencil.com/feeds/posts/default', },
	{'Nachrichten', "Noch ein Koch-Back-Blog", 'http://exactly-what-we-need.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "nonexploitinglife", 'http://nonexploitinglife.wordpress.com/feed/', },
	{'Nachrichten', "Nord & Süd", 'http://nordundsued.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "not martha", 'http://feeds.feedburner.com/notmartha', },
	{'Nachrichten', "Not So Humble Pie", 'http://feeds.feedburner.com/NotSoHumblePie', },
	{'Nachrichten', "Not Without Salt", 'http://feeds.feedburner.com/notwithoutsalt/TjyU', },
	{'Nachrichten', "Not Your Momma's Cookie", 'http://feeds.feedburner.com/NotYourMommasCookie', },
	{'Nachrichten', "O Pistachio", 'http://feeds.feedburner.com/OPistachio', },
	{'Nachrichten', "o!kuchnia", 'http://www.okuchnia.pl/feed/', },
	{'Nachrichten', "Obento Art", 'http://obentoart.com/rss', },
	{'Nachrichten', "OBERS TRIFFT SAHNE", 'http://www.oberstrifftsahne.com/feeds/posts/default', },
	{'Nachrichten', "Ofenkieker", 'http://feeds.feedburner.com/ofenkieker', },
	{'Nachrichten', "ofenlieblinge", 'http://ofenlieblinge.wordpress.com/feed/', },
	{'Nachrichten', "Oggi pane e salame, domani", 'http://www.oggipanesalamedomani.it/feed/', },
	{'Nachrichten', "Oh So Very Pretty", 'http://feeds.feedburner.com/OhSoVeryPretty', },
	{'Nachrichten', "Oh Sweet Day!", 'http://ohsweetday.com/feed', },
	{'Nachrichten', "Oh the lovely things", 'http://feeds.feedburner.com/OhTheLovelyThings', },
	{'Nachrichten', "oh!cupcakes", 'http://www.ohcupcakes.net/rss.php', },
	{'Nachrichten', "Ohhh... Mhhh...", 'http://www.ohhhmhhh.de/feed/', },
	{'Nachrichten', "Ohoh Blog", 'http://ohoh-blog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Oishii Treats", 'http://oishiitreats.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "OktoberWind", 'http://feeds.feedburner.com/Oktoberwind', },
	{'Nachrichten', "Olives for Dinner", 'http://feeds.feedburner.com/OlivesForDinner', },
	{'Nachrichten', "Omiyage Blogs", 'http://feeds.feedburner.com/OmiyageBlogs', },
	{'Nachrichten', "On Sugar Mountain", 'http://feeds.feedburner.com/onsugarmountainblog?format=xml', },
	{'Nachrichten', "Once Upon A Cupcake", 'http://onceuponacupcake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Once Upon a Cutting Board", 'http://feeds.feedburner.com/OnceUponACuttingBoard', },
	{'Nachrichten', "One Good Thing by Jillee", 'http://feeds.feedburner.com/oneGoodThingByJillee', },
	{'Nachrichten', "onelmon", 'http://feeds.feedburner.com/onelmon', },
	{'Nachrichten', "Onigiri und Sushi", 'http://onigiri-und-sushi.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pans and pots", 'http://mypansandpots.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Paper Source Blog", 'http://blog.paper-source.com/feed/', },
	{'Nachrichten', "PaperVine", 'http://feeds.feedburner.com/Papervine', },
	{'Nachrichten', "Pasta Blog", 'http://www.pastablog.de/feed/', },
	{'Nachrichten', "paules ki(t)chen", 'http://www.paules.lu/feed/', },
	{'Nachrichten', "Pays des Merveilles", 'http://rainb0wpieces.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "PDXfoodlove", 'http://pdxfoodlove.com/feed/', },
	{'Nachrichten', "Penne im Topf", 'http://www.penneimtopf.com/feeds/posts/default', },
	{'Nachrichten', "Pennies on a Platter", 'http://feeds.feedburner.com/penniesonaplatter', },
	{'Nachrichten', "Pepper", 'http://feeds.feedburner.com/pepperph', },
	{'Nachrichten', "peppermintblue", 'http://peppermintblue.wordpress.com/feed/', },
	{'Nachrichten', "Petite Cakery", 'http://petitecakery.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pham Fatale", 'http://feeds.feedburner.com/phamfatale', },
	{'Nachrichten', "PheNOMenal", 'http://phenomenalphoods.com/?feed=rss2', },
	{'Nachrichten', "photisserie", 'http://photisserie.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "piepmatz", 'http://piepmatzblog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pimpi-MEL-la", 'http://pimpimella.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pink Little Cake", 'http://pinklittlecake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pink Patisserie", 'http://pinkpatisserie.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Pink Sugar", 'http://feeds.feedburner.com/pinksugar-kessy/Xqef', },
	{'Nachrichten', "Pint Sized Baker", 'http://www.pintsizedbaker.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "PinUp Fashion", 'http://pinup-fashion.de/feed/', },
	{'Nachrichten', "pizzarossa", 'http://pizzarossa.wordpress.com/feed/', },
	{'Nachrichten', "Plötzblog", 'http://www.ploetzblog.de/feed/', },
	{'Nachrichten', "Poires au Chocolat", 'http://feeds2.feedburner.com/PoiresauChocolat', },
	{'Nachrichten', "Portuguese Girl Cooks", 'http://feeds.feedburner.com/PortugueseGirlCooks', },
	{'Nachrichten', "Post aus meiner Küche", 'http://www.postausmeinerkueche.de/feed/', },
	{'Nachrichten', "Postreadicción", 'http://postreadiccion.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Prairiesummers", 'http://prairiesummers.wordpress.com/feed/', },
	{'Nachrichten', "pretty polymath", 'http://prettypolymath.com/feed/', },
	{'Nachrichten', "PrettyBaked", 'http://prettybaked.pl/index.php/feed/', },
	{'Nachrichten', "Prevention RD", 'http://feeds.feedblitz.com/preventionrd&x=1', },
	{'Nachrichten', "Princess in the Kitchen", 'http://princessinthekitchen.wordpress.com/feed/', },
	{'Nachrichten', "Prinz Leinad", 'http://prinzleinad.wordpress.com/feed/', },
	{'Nachrichten', "Produce on Parade", 'http://produceonparade.wordpress.com/feed/', },
	{'Nachrichten', "PROUD ITALIAN COOK", 'http://www.prouditaliancook.com/feeds/posts/default', },
	{'Nachrichten', "Puppenzimmer", 'http://www.puppenzimmer.com/feeds/posts/default', },
	{'Nachrichten', "pure and noble", 'http://pureandnoble.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Pure Vegetarian", 'http://feeds.feedburner.com/purevege/Erml', },
	{'Nachrichten', "Purple Moments", 'http://www.purple-moments.com/feed/', },
	{'Nachrichten', "Pâtisserie Nadine", 'http://blog.nadineperera.de/feeds/posts/default', },
	{'Nachrichten', "Quiche-a-Week", 'http://quicheaweek.wordpress.com/feed/', },
	{'Nachrichten', "Rachel Cooks", 'http://feeds.feedblitz.com/rachelcooks', },
	{'Nachrichten', "raspberri cupcakes", 'http://feeds.feedburner.com/RaspberriCupcakes', },
	{'Nachrichten', "Rawmazing Raw Food", 'http://feeds.feedburner.com/rawmazing?format=xml', },
	{'Nachrichten', "Rawsday", 'http://rawsday.wordpress.com/feed/', },
	{'Nachrichten', "re.", 'http://recreatedesigncompany.com/blog/feed/', },
	{'Nachrichten', "Recent Instructables", 'http://feeds.feedburner.com/instructables/RiBN', },
	{'Nachrichten', "Recipe By Photo", 'http://www.recipebyphoto.com/feed/', },
	{'Nachrichten', "Recipe Snobs", 'http://feeds.feedburner.com/FoodSnots', },
	{'Nachrichten', "Reclaiming Provincial", 'http://www.reclaimingprovincial.com/feed/', },
	{'Nachrichten', "Red Shallot Kitchen", 'http://www.redshallotkitchen.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Reine Topfsache", 'http://www.reinetopfsache.de/?feed=rss2', },
	{'Nachrichten', "Relevé Design", 'http://www.relevedesign.com/feed/', },
	{'Nachrichten', "relleoMein", 'http://relleomein.wordpress.com/feed/', },
	{'Nachrichten', "Rezeptbuch", 'http://feeds.feedburner.com/NeueRezepteAufRezeptebuchcom', },
	{'Nachrichten', "Rezeptefuchs", 'http://www.rezeptefuchs.de/Syndication/Rezept/erstmalig_veroeffentlicht/10/Rss20', },
	{'Nachrichten', "rezeptepenny", 'http://rezeptepenny.wordpress.com/feed/', },
	{'Nachrichten', "roboto liebt", 'http://robotiliebt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Rock n Roll Bride", 'http://feeds2.feedburner.com/rocknrollbride/index', },
	{'Nachrichten', "rock the kitchen!", 'http://www.rock-the-kitchen.de/feed/', },
	{'Nachrichten', "Ronny Kocht", 'http://ronnykocht.wordpress.com/feed/', },
	{'Nachrichten', "Roost", 'http://www.roostblog.com/roost/rss.xml', },
	{'Nachrichten', "roughcutblog", 'http://feeds.feedburner.com/roughcutblog/xUPB', },
	{'Nachrichten', "Rústica", 'http://www.rusttica.com/feeds/posts/default', },
	{'Nachrichten', "S-Küche", 'http://s-kueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "sabrinasue", 'http://sabrinasue.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sallys Baking Addiction", 'http://feeds2.feedburner.com/sallysbakingaddiction', },
	{'Nachrichten', "saltet lemons", 'http://loisslokoski.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Salz, Pfeffer, Kokosnuss", 'http://salzpfefferkokosnuss.wordpress.com/feed/', },
	{'Nachrichten', "samtundsahne", 'http://samtundsahne.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sandi´s Süsse Welt", 'http://sandis-suesse-welt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sarahs Krisenherd", 'http://sarahskrisenherd.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sarahs Torten und Cupcakes", 'http://sarahs-torten.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "sasibellas creativity", 'http://sasibella.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "SaskiarundumdieUhr", 'http://saskiarundumdieuhr.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Savory simple", 'http://feeds.feedburner.com/SavorySimple', },
	{'Nachrichten', "Schatz? Gibt es das morgen nochmal?", 'http://leckerinschwaben.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Schneewittchens Apfel", 'http://schneewittchens-apfel.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "schnin's kitchen", 'http://schninskitchen.wordpress.com/feed/', },
	{'Nachrichten', "SchokoCupcakes", 'http://schokocupcakes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "SchokoFaden", 'http://schokofaden.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Schokoladentafel", 'http://www.schokoladentafel.com/feed/', },
	{'Nachrichten', "Schön und fein", 'http://www.schoen-und-fein.de/feed/', },
	{'Nachrichten', "Schöner Tag noch!", '"http://schoenertagnoch.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Scratching Canvas", 'http://www.scratchingcanvas.com/feeds/posts/default', },
	{'Nachrichten', "seidenfein 's Dekoblog", 'http://seidenfein.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sekundentakt", 'http://dassternenkind.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Selbst Eis machen", 'http://www.eis-machen.de/feed/', },
	{'Nachrichten', "Serendipity Blog", 'http://www.serendipity-blog.de/feed/', },
	{'Nachrichten', "Seviesphere", 'http://seviesphere.net/feed/', },
	{'Nachrichten', "Shared Appetite", 'http://sharedappetite.com/feed/', },
	{'Nachrichten', "She Exists", 'http://feeds.feedburner.com/shexists/jzpg', },
	{'Nachrichten', "SHELIKES", 'http://www.shelikes.de/feeds/posts/default', },
	{'Nachrichten', "Shermins magischer Kessel", 'ttp://www.magischer-kessel.de/feed/', },
	{'Nachrichten', "Shift Ctrl ART Blog", 'http://feeds.feedburner.com/ShiftCtrlArt', },
	{'Nachrichten', "Shrimp Salad Circus", 'http://feeds.feedburner.com/blogspot/fkuH', },
	{'Nachrichten', "Shugary Sweets", 'http://feeds.feedburner.com/ShugarySweets', },
	{'Nachrichten', "simple craves & olive oil", 'http://feeds.feedburner.com/simplecravesandoliveoil', },
	{'Nachrichten', "Simply Delicious", 'http://feeds.feedburner.com/simply-delicious?format=xml', },
	{'Nachrichten', "Simply Recipes", 'http://feeds.feedburner.com/elise/simplyrecipes', },
	{'Nachrichten', "Simply Sweets by Honeybee", 'http://www.simplysweetsbyhoneybee.com/feeds/posts/default', },
	{'Nachrichten', "SkinnyNOTSkinny ", 'http://skinnynotskinny.com/feed/', },
	{'Nachrichten', "Skip To My Lou", 'http://www.skiptomylou.org/feed/', },
	{'Nachrichten', "Smart Cookie", 'http://smartcookiebakes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "smitten kitchen", 'http://feeds.feedburner.com/smittenkitchen', },
	{'Nachrichten', "So, How*s The Taste?", 'http://feeds.feedburner.com/SoHowsItTaste', },
	{'Nachrichten', "so.... this is Bento?!", 'http://thisisbento.wordpress.com/feed/', },
	{'Nachrichten', "sodapop design", 'http://sodapop-design.de/feed/', },
	{'Nachrichten', "Some Kitchen Stories", 'http://somekitchenstories.com/feed/', },
	{'Nachrichten', "Some the Wiser", 'http://feeds.feedburner.com/SomeTheWiser', },
	{'Nachrichten', "SonntagsFräulein", 'http://blog.sonntagsfraeulein.de/feed/', },
	{'Nachrichten', "Sonoma Bento", 'http://sonomabento.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "sophistimom", 'http://www.sophistimom.com/feed/', },
	{'Nachrichten', "soul soup soap", 'http://soulsoupsoap.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Spice Up Your Life With a Taste of Japan", 'http://taste-of-japan.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Spilling my Brains.....", 'http://missnightmares.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Splash of Something", 'http://splashofsomething.com/feed/', },
	{'Nachrichten', "Spoon Fork Bacon", 'http://feeds.feedburner.com/SpoonForkBacon', },
	{'Nachrichten', "Spoonful", 'http://www.spoonfulblog.com/feeds/posts/default', },
	{'Nachrichten', "Sprinkle Bakes", 'http://feeds.feedburner.com/SprinkleBakes', },
	{'Nachrichten', "Sprinkles in Springs", 'http://sprinklesinsprings.com/feed', },
	{'Nachrichten', "Squeaky Swing", 'http://squeakyswing.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Squirrelly Minds", 'http://feeds.feedburner.com/SquirrellyMinds?format=xml', },
	{'Nachrichten', "Stars for Streetlights", 'http://feeds.feedburner.com/starsforstreetlights/GIlF', },
	{'Nachrichten', "Step by Step", 'http://cairnsbirdwing.wordpress.com/feed/', },
	{'Nachrichten', "stir + whisk", 'http://www.stirandwhisk.com/feeds/posts/default', },
	{'Nachrichten', "StitchPunk", 'http://www.urbanthreads.com/blog/?feed=rss2', },
	{'Nachrichten', "strictlypaper", 'http://feeds.feedburner.com/strictlypaper', },
	{'Nachrichten', "Studentenküche", 'http://www.studentenkueche.com/category/rezepte/feed/', },
	{'Nachrichten', "Studio DIY", 'http://www.studiodiy.com/feed/', },
	{'Nachrichten', "Stuff Steph Does", 'http://feeds.feedburner.com/StuffStephDoes', },
	{'Nachrichten', "stylegawker", 'http://feeds2.feedburner.com/stylegawkerhttp://feeds2.feedburner.com/stylegawker', },
	{'Nachrichten', "Sugar & Cloth", 'http://feeds.feedburner.com/SugarCloth', },
	{'Nachrichten', "Sugar and Charm", 'http://www.sugarandcharmblog.com/feeds/posts/default', },
	{'Nachrichten', "Sugar and Spice", 'http://sugarandspice-foodblog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sugar for the Brain", 'http://feeds.feedburner.com/SugarForTheBrain', },
	{'Nachrichten', "Sugar Stories", 'http://www.sugar-stories.com/feeds/posts/default', },
	{'Nachrichten', "Sugar Swings! Serve Some", 'http://sugarswings.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sugar Thumb", 'http://sugarthumb.wordpress.com/feed/', },
	{'Nachrichten', "SugarHero!", 'http://www.sugarhero.com/feed/', },
	{'Nachrichten', "SugaryWinzy", 'http://feeds.feedburner.com/sugarywinzy?format=xml', },
	{'Nachrichten', "Sushirolle", 'http://www.sushirolle.de/index.php?format=feed&type=atom', },
	{'Nachrichten', "Sushiselbstmachen", 'http://www.sushiselbstmachen.de/feed/', },
	{'Nachrichten', "Sweet Anne Handcrafted Designs", 'http://feeds.feedburner.com/SweetAnneHandcraftedDesigns', },
	{'Nachrichten', "Sweet Boake", 'http://sweetboake.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sweet Creations by Debbie", 'http://sweetsbydebbie.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Sweet Little Thang", 'http://sweetlittlethang.wordpress.com/feed/', },
	{'Nachrichten', "sweet times", 'http://meliha-sweettimes.com/feed/', },
	{'Nachrichten', "sweet trolley", 'http://sweet-trolley.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "SweetAmbs", 'https://www.sweetambs.com/feed/', },
	{'Nachrichten', "Sweetapolita", 'http://feeds.feedburner.com/sweetapolita', },
	{'Nachrichten', "Sweetie's Home", 'http://www.sweetie-home.it/index.php/feed/', },
	{'Nachrichten', "Sweetopia", 'http://sweetopia.net/feed/', },
	{'Nachrichten', "SweetsBar", 'http://sweetsbar.derschoepfer.de/feed/', },
	{'Nachrichten', "Süße Kreativität", 'http://schokolia.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Süße Versuchung", 'http://brigittestorten.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Table for Two", 'http://feeds.feedburner.com/TableForTwoBlog', },
	{'Nachrichten', "Tablespoon Blogs", 'http://pipes.yahoo.com/pipes/pipe.run?_id=3573ed1ff2c7c4ad916db28052b5a61c&_render=rss', },
	{'Nachrichten', "Tacoweb", 'http://www.tacoweb.de/feed/', },
	{'Nachrichten', "Tales of a Kitchen", 'http://talesofakitchen.com/feed/', },
	{'Nachrichten', "talie fee", 'http://taliefee.de/feed/', },
	{'Nachrichten', "Tanya's Cakes", 'http://tanitac.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "tartas y nubes de azúcar", 'http://tartasynubes.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Tartelette", 'http://feeds.feedburner.com/tartelette', },
	{'Nachrichten', "Tassenkuchen - Bäckerei", 'http://tassenkuchen-baeckerei.blogspot.de/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Taste and Tell", 'http://feeds.feedburner.com/tasteandtellblog?format=xml', },
	{'Nachrichten', "Tasteologie", 'http://tasteologie.notcot.org/atom.php', },
	{'Nachrichten', "Tastes of Lizzy T's", 'http://feeds.feedburner.com/TastesOfLizzyT?format=xml', },
	{'Nachrichten', "tastesheriff", 'http://www.tastesheriff.com/feed/', },
	{'Nachrichten', "TasteSpotting", 'http://www.tastespotting.com/rss', },
	{'Nachrichten', "Tasty Bento", 'http://feeds.feedburner.com/blogspot/CBylD', },
	{'Nachrichten', "Tattooed on my heart", 'http://tattooed-onmyheart.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Technicolor Kitchen", 'http://feeds.feedburner.com/TechnicolorKitchen-EnglishVersion', },
	{'Nachrichten', "Testado, Provado e Aprovado!", 'http://feeds.feedburner.com/blogspot/FVhzT', },
	{'Nachrichten', "Thank you for eating", 'http://zinkplusc.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "That Skinny Chick Can Bake", 'http://feeds.feedburner.com/thatskinnychickcanbake/mcbO?format=xml', },
	{'Nachrichten', "The 36th AVENUE", 'http://feeds.feedburner.com/The36thAvenue', },
	{'Nachrichten', "The Baker Chick", 'http://feeds.feedburner.com/TheBakerChick', },
	{'Nachrichten', "the baking cup", 'http://thebakingcup.com/feed/', },
	{'Nachrichten', "The Baking Robot", 'http://feeds.feedburner.com/TheBakingRobot', },
	{'Nachrichten', "The Beeroness", 'http://feeds.feedburner.com/thebeeroness?format=xml ', },
	{'Nachrichten', "The Best Cupcake Recipes", 'http://thebestcupcakerecipes.com/feed/', },
	{'Nachrichten', "The Boxed Party Company", 'http://theboxedparty.wordpress.com/feed/', },
	{'Nachrichten', "The Café Sucré Farine", 'http://feeds.feedburner.com/blogspot/KEYPqf?format=xml', },
	{'Nachrichten', "The Cheese Thief", 'http://feeds.feedburner.com/TheCheeseThief', },
	{'Nachrichten', "The Collegiate Baker", 'http://www.thecollegiatebaker.com/feeds/posts/default', },
	{'Nachrichten', "The Comfort of Cooking", 'http://feeds.feedburner.com/TheComfortOfCooking?format=xml', },
	{'Nachrichten', "The Culinary Trial", 'http://www.the-culinary-trial.de/feed/', },
	{'Nachrichten', "The Cupcake Blog", 'http://feeds.feedburner.com/TheCupcakeBlog', },
	{'Nachrichten', "The Cupcake Daily Blog", 'http://thecupcakedailyblog.com/feed/', },
	{'Nachrichten', "The Dainty Squid", 'http://daintysquid.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The Decorated Cookie", 'http://thedecoratedcookie.com/feed/atom', },
	{'Nachrichten', "The Denim Apron", 'http://feeds.feedburner.com/thedenimapron?format=xml', },
	{'Nachrichten', "The Devil's Food Advocate", 'http://thedevilsfoodadvocate.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The DIY Queen", 'http://www.diy-queen.com/feed/', },
	{'Nachrichten', "The Extraordinary Art of Cake", 'http://www.theextraordinaryartofcake.com/feeds/posts/default', },
	{'Nachrichten', "The Fab Web", 'http://feeds.feedburner.com/thefabweb', },
	{'Nachrichten', "The Flourishing Foodie", 'http://feeds.feedburner.com/TheFlourishingFoodie', },
	{'Nachrichten', "The Galley Gourmet", 'http://feeds.feedburner.com/thegalleygourmet/Ihxj', },
	{'Nachrichten', "The Ginger snap Girl", 'http://thegingersnapgirl.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The Gouda Life", 'http://thegoudalife.tumblr.com/rss', },
	{'Nachrichten', "The Gunny Sack", 'http://feeds.feedburner.com/TheGunnySack', },
	{'Nachrichten', "The Hopeless Housewife", 'http://www.thehopelesshousewife.com/feed/', },
	{'Nachrichten', "The Italian Dish", 'http://theitaliandishblog.com/imported-20090913150324/rss.xml', },
	{'Nachrichten', "The Kitchen Paper", 'http://feeds.feedburner.com/thekitchenpaper', },
	{'Nachrichten', "The Kitchn", 'http://feeds.thekitchn.com/apartmenttherapy/thekitchn', },
	{'Nachrichten', "The Little Epicurean", 'http://www.thelittleepicurean.com/feed', },
	{'Nachrichten', "The Lotus and the Artichoke", 'http://www.lotusartichoke.com/feed/', },
	{'Nachrichten', "The Merrythought", 'http://themerrythought.com/feed/', },
	{'Nachrichten', "The Messy Baker", 'http://themessybaker.com/feed/', },
	{'Nachrichten', "The Midnight Baker", 'http://feeds.feedburner.com/blogspot/INVQW', },
	{'Nachrichten', "The moonblush Baker", 'http://themoonblushbaker.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The Novice Chef Blog", 'http://feeds.feedblitz.com/thenovicechefblog2&x=1', },
	{'Nachrichten', "The Novice Housewife", 'http://feeds.feedburner.com/novicehousewife/YqiK?format=xml', },
	{'Nachrichten', "The Partiologist", 'http://feeds.feedburner.com/thepartiologist?format=xml', },
	{'Nachrichten', "The Pastry Affair", 'http://feeds.feedburner.com/thepastryaffair/', },
	{'Nachrichten', "The Pescetarian and the Pig", 'http://feeds.feedburner.com/ThePescetarianAndThePig?format=xml', },
	{'Nachrichten', "The Plumed Nest", 'http://www.theplumednest.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "The Realistic Nutritionist", 'http://feeds.feedburner.com/nutritionforus?format=xml', },
	{'Nachrichten', "The Red Thread", 'http://feeds.feedburner.com/TheRedThread', },
	{'Nachrichten', "The Scrumptious Pumpkin", 'http://thescrumptiouspumpkin.com/feed/', },
	{'Nachrichten', "The Slow Roasted Italian", 'http://feeds.feedburner.com/TheSlowRoastedItalian', },
	{'Nachrichten', "The Stay At Home Chef", 'http://feeds.feedburner.com/TheStayAtHomeChef?format=xml', },
	{'Nachrichten', "THE STEPFORD HUSBAND", 'http://thestepfordhusband.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The Sweet Adventures of  Sugar Belle", 'http://feeds.feedburner.com/TheSweetAdventuresOfSugarbelle', },
	{'Nachrichten', "The Sweet Life", 'http://feeds2.feedburner.com/thesweetlifeonline/Aclf', },
	{'Nachrichten', "The Sweetest Occasion", 'http://feeds.feedburner.com/TheSweetestOccasion', },
	{'Nachrichten', "The Sweetest Vegan", 'http://thesweetestvegan.com/feed/', },
	{'Nachrichten', "the tolerant vegan", 'http://feeds.feedburner.com/TheTolerantVegan?format=xml', },
	{'Nachrichten', "The Vegan Stoner", 'http://theveganstoner.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "The Vegetarian Diaries", 'http://vegetarian-diaries.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "The Wandering Eater", 'http://feeds2.feedburner.com/wordpress/rqmY', },
	{'Nachrichten', "The Wedding Chicks", 'http://www.weddingchicks.com/feed/', },
	{'Nachrichten', "The Yum Yum Factor", 'http://theyumyumfactor.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "THEGOODPLATE", 'http://feeds.feedburner.com/THEGOODPLATE', },
	{'Nachrichten', "Things we make", 'http://thingswemake.wordpress.com/feed/', },
	{'Nachrichten', "This Gal Cooks", 'http://feeds.feedburner.com/thisgalcooks?format=xml', },
	{'Nachrichten', "This Is My Inspiration", 'http://myinspiration.tv/feed/', },
	{'Nachrichten', "Thistlewood Farm", 'http://feeds.feedburner.com/ThistlewoodFarm', },
	{'Nachrichten', "three is a party", 'http://www.three-is-a-party.de/feed/', },
	{'Nachrichten', "TikkiDo", 'http://www.tikkido.com/rss.xml', },
	{'Nachrichten', "Tines vegane Backstube", 'http://www.tinesveganebackstube.de/feed/', },
	{'Nachrichten', "Tiny Urban Kitchen", 'http://feeds.feedburner.com/JgleesFoodMusings?format=xml', },
	{'Nachrichten', "titatoni", 'http://titatoni.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "TLT - The Little Things", 'http://tlt-thelittlethings.com/feed/', },
	{'Nachrichten', "To Food with Love", 'http://feeds.feedburner.com/blogspot/wpruv', },
	{'Nachrichten', "tobias kocht!", 'http://feeds.feedburner.com/TobiasKocht', },
	{'Nachrichten', "Tomateninsel", 'http://tomateninsel.de/rss/', },
	{'Nachrichten', "Torie Jayne", 'http://feeds.feedburner.com/TorieJayne', },
	{'Nachrichten', "Torten Dekorieren", 'http://www.torten-dekorieren.de/blog/feed/', },
	{'Nachrichten', "Tortenelfes Blog", 'http://tortenelfe.blogspot.de//feeds/posts/default', },
	{'Nachrichten', "Tortentantes Tortenwelt", 'http://feeds.feedburner.com/blogspot/aoIIk', },
	{'Nachrichten', "Tortentraum", 'http://tortenhimmel.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Travel For Taste", 'http://travel4taste.com/feed/', },
	{'Nachrichten', "Tutti Dolci", 'http://feeds.feedburner.com/TuttiDolci?format=xml', },
	{'Nachrichten', "Twin Food", 'http://twin-food.dk/feed/', },
	{'Nachrichten', "Two Loves Studio", 'http://twolovesstudio.com/feed/', },
	{'Nachrichten', "Two Peas & Their Pod", 'http://feeds.feedburner.com/twopeasandtheirpod/rNNF', },
	{'Nachrichten', "twoodledrum", 'http://twoodledrum.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Törtchen und andere Leckereien", 'http://toertchenundandereleckereien.wordpress.com/feed/', },
	{'Nachrichten', "Un Amore Custom Designs", 'http://unamore.wordpress.com/feed/', },
	{'Nachrichten', "Una streghetta in cucina", 'http://www.streghettaincucina.com/feeds/posts/default', },
	{'Nachrichten', "Unverbissen vegetarisch", 'http://www.unverbissen-vegetarisch.de/feed/', },
	{'Nachrichten', "Upcycle That", 'http://www.upcyclethat.com/feed/', },
	{'Nachrichten', "Upcycle Us", 'http://upcycleus.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "USA kulinarisch", 'http://www.usa-kulinarisch.de/feed/', },
	{'Nachrichten', "uTry.it", 'http://feeds.feedburner.com/uTryit', },
	{'Nachrichten', "Valentinas-Kochbuch", 'http://valentinas-kochbuch.de/feed/', },
	{'Nachrichten', "vanillakitchen", 'http://www.vanillakitchen.de/feed/', },
	{'Nachrichten', "Veg Recipes of India", 'http://feeds.feedburner.com/VegRecipesOfIndia ', },
	{'Nachrichten', "Vegan Guerilla", 'http://www.veganguerilla.de/feed/', },
	{'Nachrichten', "Vegan Nom Noms", 'http://vegannomnoms.blogspot.com/feeds/posts/default?alt=rss', },
	{'Nachrichten', "Vegan Yack Attack", 'http://veganyackattack.com/feed/', },
	{'Nachrichten', "Vegan Yumminess", 'http://feeds.feedburner.com/VeganYumminess', },
	{'Nachrichten', "vegan-sein", 'http://www.vegan-sein.de/feed', },
	{'Nachrichten', "vegan-und-lecker", 'http://vegan-und-lecker.de/feed/rss/', },
	{'Nachrichten', "Vegane Versuchsküche", 'http://veganeversuchskueche.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "veganolution", 'http://veganolution.wordpress.com/feed/', },
	{'Nachrichten', "Veganpassion", 'http://veganpassion.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Veganvsmeat", 'http://www.veganvsmeat.de/feed', },
	{'Nachrichten', "VeganYumYum", 'http://veganyumyum.com/feed/', },
	{'Nachrichten', "Vegetarische Rezepte", 'http://feeds.feedburner.com/RezeptVegetarisch', },
	{'Nachrichten', "Vegetarische Rezepte", 'http://www.vegetarische-rezepte.com/assets/rss/news.xml', },
	{'Nachrichten', "Veggie-Bento", 'http://www.veggie-bento.com/feed/', },
	{'Nachrichten', "veggie4friends", 'http://veggie4friends.de/feed/', },
	{'Nachrichten', "Veggieful", 'http://www.veggieful.com/feeds/posts/default', },
	{'Nachrichten', "Verrückt nach Hochzeit", 'http://www.verrückt-nach-hochzeit.de/feed/', },
	{'Nachrichten', "Victoria's Little Secrets", 'http://aboutvictoriaslittlesecrets.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Vietnamesisches Kochbuch", 'http://vietkochen.blog.de/feed/rss2/posts/', },
	{'Nachrichten', "VIKALINKA", 'http://vikalinka.com/feed/', },
	{'Nachrichten', "Visual.ly", 'http://visual.ly/top_rss.xml', },
	{'Nachrichten', "Vivid Please", 'http://vividplease.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Von Kuchen und Keksen", 'http://vonkuchenundkeksen.wordpress.com/feed/', },
	{'Nachrichten', "Wagashi Maniac", 'http://blog.wagashi-net.de/feed/', },
	{'Nachrichten', "Wantist", 'http://feeds.feedburner.com/WantistBlog', },
	{'Nachrichten', "warmhotchocolate", 'http://feeds.feedburner.com/Warmhotchocolate', },
	{'Nachrichten', "wastecooking", 'http://www.wastecooking.com/feed/', },
	{'Nachrichten', 'We love Pasta', 'http://www.we-love-pasta.de/feed/ ', },
	{'Nachrichten', 'Wedding Cakes', 'http://weddingcakesx.com/feed/', },
	{'Nachrichten', 'Weelicious', 'http://weelicious.com/feed/', },
	{'Nachrichten', 'what Ina loves', 'http://cityglamblog.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "What Katie's Baking", 'http://feeds.feedburner.com/what-katies-baking', },
	{'Nachrichten', 'What Should I Eat For Breakfast Today?', 'http://whatshouldieatforbreakfasttoday.com/rss', },
	{'Nachrichten', 'What The Fruitcake?!', 'http://www.mandymortimer.com/latest-posts/rss.xml', },
	{'Nachrichten', "What's for dinner?", 'http://feeds.feedburner.com/blogspot/yMyZO', },
	{'Nachrichten', "whatever's left", 'http://www.whateversleft.org/feed/', },
	{'Nachrichten', 'When Geeks Wed', 'http://feeds.feedburner.com/whengeekswed/WCbt', },
	{'Nachrichten', 'Whisk Kid', 'http://feeds.feedburner.com/blogspot/ZdjH', },
	{'Nachrichten', 'Will Cook For Friends', 'http://www.willcookforfriends.com/feeds/posts/default', },
	{'Nachrichten', 'Willow Bird Baking', 'http://willowbirdbaking.com/feed/', },
	{'Nachrichten', 'Wishes and Dishes', 'http://feeds.feedburner.com/WishesAndDishes?format=xml', },
	{'Nachrichten', 'With Sprinkles on Top', 'http://feeds.feedburner.com/WithSprinklesOnTop', },
	{'Nachrichten', "Wo geht's zum Gemüseregal", 'http://www.gemueseregal.de/feed/', },
	{'Nachrichten', 'Wokking it', 'http://wokkingit.wordpress.com/feed/', },
	{'Nachrichten', 'Wolkenfees Küchenwerkstatt', 'http://wolkenfeeskuechenwerkstatt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', 'Working Mom Cook Fusion', 'http://www.workingmomcookfusion.com/feed/', },
	{'Nachrichten', 'Worth Pinning', 'http://feeds.feedburner.com/WorthPinning', },
	{'Nachrichten', 'Wunderfitzig', 'http://wunderfitzig.bplaced.net/?feed=rss2', },
	{'Nachrichten', "Yammie's Noshery", 'http://feeds.feedburner.com/blogspot/RppsK', },
	{'Nachrichten', 'yellow girl', 'http://www.yellowgirl.at/feed/', },
	{'Nachrichten', 'You Too Can Cook', 'http://feeds.feedburner.com/YouTooCanCook', },
	{'Nachrichten', 'Your Cup of Cake', 'http://feeds.feedburner.com/YourCupofCake', },
	{'Nachrichten', "Yue's Handicrafts", 'http://feeds.feedburner.com/blogspot/nUYzv', },
	{'Nachrichten', 'Yukitchen', 'http://yukitchen.wordpress.com/feed/', },
	{'Nachrichten', 'Yum Goggle Gallery ', 'http://feeds.feedburner.com/YumGoggleGallery', },
	{'Nachrichten', 'Yum-Yum Bento Box', 'http://www.yumyumbento.com/feed/ ', },
	{'Nachrichten', 'Yummly', 'http://www.yummly.com/blog/feed/', },
	{'Nachrichten', 'yummydesign', 'http://muffin-mafia.blogspot.com/feeds/posts/default', },
	{'Nachrichten', 'Zaboravljene poslastice', 'http://tortatorta.blogspot.com/feeds/posts/default', },
	{'Nachrichten', 'Zen Can Cook', 'http://www.zencancook.com/feed/rss/', },
	{'Nachrichten', 'ZEN PENCILS', 'http://feeds.feedburner.com/zenpencils?format=xml', },
	{'Nachrichten', 'Zimtzauber & Zuckernebel', 'http://zuckernebel.blogspot.com/feeds/posts/default', },
	{'Nachrichten', "Zizi's Adventures", 'http://feeds.feedburner.com/ziziadventures', },
	{'Nachrichten', 'Zoe Bakes', 'http://feeds.feedburner.com/ZoeBakes?format=xml', },
	{'Nachrichten', 'Zoom Yummy', 'http://zoomyummy.com/feed/', },
	{'Nachrichten', 'Zucker, Zimt und Liebe', 'http://zuckerzimtundliebe.wordpress.com/feed/', },
	{'Nachrichten', 'zuckerimsalz', 'http://zuckerimsalz.wordpress.com/feed/', },
	{'Nachrichten', 'ZUCKERWELT', 'http://fabelhaftezuckerwelt.blogspot.com/feeds/posts/default', },
	{'Nachrichten', 'zumbackenverfuehrt', 'http://zumbackenverfuehrt.wordpress.com/feed/', },
	{'Nachrichten', '{ himbeermarmelade }', 'http://feeds.feedburner.com/himbeermarmeladede?format=xml', },
}