[styleGcalBackground]
ImageName = #@#Images\Gcal\Background.png
ImageAlpha = 200
W = #SCREENAREAWIDTH#
H = 140
ImageRotate = 180

[styleGcalDate]
FontFace = #FontFamily#
FontSize = #FontSizeSmall#
FontColor= #FontColorLow#
StringAlign = Left
StringCase = None
ClipString = 1
AntiAlias = 1
H = 14
X = 0r
Y = 0r
W = #ColumWidth#
Text = Dienstag, 08 Jan

[styleGcalBar]
X = -5r
Y = 18r
W = 3
H = 12
SolidColor = FF0000

[styleGcalDesc]
FontFace = #FontFamily#
FontSize = #FontSizeMedium#
FontColor = #FontColorHigh#
StringAlign = Left
StringCase = None
AntiAlias = 1
ClipString = 1
H = 16
X = 2R
Y = -2r
W = 270
Text = "[Geburtstag] Das ist ein Geburtstag"

[styleGcalMoreEvents]
X = -6r
Y = 18r
Text = *

[styleGcalColumn]
SolidColor = FFFFFF99
W = 250
H = 70
X = 10R
Y = 0r
AntiAlias = 1

