; Top
; ==================================================
[iBackgroundTL]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerTopLeft

[iBackgroundT]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeTop

[iBackgroundTR]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerTopRight

; Center
; ==================================================
[iForegroundLeft]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeLeft

[iForeground]
Meter = Image
MeterStyle = yForeground

[iForegroundRight]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeRight

; Bottom
; ==================================================
[iForegroundCornerBottomLeft]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerBottomLeft

[iForegroundBottom]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeBottom

[iForegroundCornerBottomRight]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerBottomRight





