; ==================================================
; Background 
; ==================================================
; Corner
[meterFeedReaderBackgroundCornerTL]
Meter = Roundline
MeterStyle = styleFeedReaderBackgroundCorner|styleFeedReaderBackgroundCornerTopLeft

[meterFeedReaderBackgroundCornerTR]
Meter = Roundline
MeterStyle = styleFeedReaderBackgroundCorner|styleFeedReaderBackgroundCornerTopRight

[meterFeedReaderBackgroundCornerBL]
Meter = Roundline
MeterStyle = styleFeedReaderBackgroundCorner|styleFeedReaderBackgroundCornerBottomLeft

[meterFeedReaderBackgroundCornerBR]
Meter = Roundline
MeterStyle = styleFeedReaderBackgroundCorner|styleFeedReaderBackgroundCornerBottomRight

; Edges
[meterFeedReaderBackgroundTop]
Meter = Image
MeterStyle = styleFeedReaderBackgroundEdge|styleFeedReaderBackgroundEdgeTop

[meterFeedReaderBackgroundBottom]
Meter = Image
MeterStyle = styleFeedReaderBackgroundEdge|styleFeedReaderBackgroundEdgeBottom

[meterFeedReaderBackgroundLeft]
Meter = Image
MeterStyle = styleFeedReaderBackgroundEdge|styleFeedReaderBackgroundEdgeLeft

[meterFeedReaderBackgroundRight]
Meter = Image
MeterStyle = styleFeedReaderBackgroundEdge|styleFeedReaderBackgroundEdgeRight

; Center
[meterFeedReaderBackground]
Meter = Image
MeterStyle = styleFeedReaderBackground