; ==================================================
; Entry
;
; Displays all Entries of selected feed
; ==================================================
; Entry 1
[meterFeedReaderEntryDummy1]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow1|styleFeedReaderEntryDummyCol1

[meterFeedReaderEntryDesc1]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry1#

[meterFeedReaderEntry1]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\example.jpg
LeftMouseUpAction = #HideEntry1#

[meterFeedReaderEntryTitle1]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry1#


; Entry 2
[meterFeedReaderEntryDummy2]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow1|styleFeedReaderEntryDummyCol2

[meterFeedReaderEntryDesc2]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry2#

[meterFeedReaderEntry2]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\example.png
LeftMouseUpAction = #HideEntry2#

[meterFeedReaderEntryTitle2]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry2#


; Entry 3
[meterFeedReaderEntryDummy3]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow1|styleFeedReaderEntryDummyCol3

[meterFeedReaderEntryDesc3]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry3#

[meterFeedReaderEntry3]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry3#

[meterFeedReaderEntryTitle3]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry3#


; Entry 4
[meterFeedReaderEntryDummy4]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow2|styleFeedReaderEntryDummyCol1

[meterFeedReaderEntryDesc4]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry4#

[meterFeedReaderEntry4]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry4#

[meterFeedReaderEntryTitle4]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry4#


; Entry 5
[meterFeedReaderEntryDummy5]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow2|styleFeedReaderEntryDummyCol2

[meterFeedReaderEntryDesc5]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry5#

[meterFeedReaderEntry5]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry5#

[meterFeedReaderEntryTitle5]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry5#


; Entry 6
[meterFeedReaderEntryDummy6]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow2|styleFeedReaderEntryDummyCol3

[meterFeedReaderEntryDesc6]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry6#

[meterFeedReaderEntry6]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry6#

[meterFeedReaderEntryTitle6]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry6#


; Entry 7
[meterFeedReaderEntryDummy7]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow3|styleFeedReaderEntryDummyCol1

[meterFeedReaderEntryDesc7]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry7#

[meterFeedReaderEntry7]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry7#

[meterFeedReaderEntryTitle7]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry7#


; Entry 8
[meterFeedReaderEntryDummy8]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow3|styleFeedReaderEntryDummyCol2

[meterFeedReaderEntryDesc8]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry8#

[meterFeedReaderEntry8]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry8#

[meterFeedReaderEntryTitle8]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry8#


; Entry 9
[meterFeedReaderEntryDummy9]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow3|styleFeedReaderEntryDummyCol3

[meterFeedReaderEntryDesc9]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry9#

[meterFeedReaderEntry9]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry9#

[meterFeedReaderEntryTitle9]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry9#


; Entry 10
[meterFeedReaderEntryDummy10]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow4|styleFeedReaderEntryDummyCol1

[meterFeedReaderEntryDesc10]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry10#

[meterFeedReaderEntry10]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry10#

[meterFeedReaderEntryTitle10]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry10#


; Entry 11
[meterFeedReaderEntryDummy11]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow4|styleFeedReaderEntryDummyCol2

[meterFeedReaderEntryDesc11]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry11#

[meterFeedReaderEntry11]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry11#

[meterFeedReaderEntryTitle11]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry11#


; Entry 12
[meterFeedReaderEntryDummy12]
Meter = Image
MeterStyle = styleFeedReaderEntryDummy|styleFeedReaderEntryDummyRow4|styleFeedReaderEntryDummyCol3

[meterFeedReaderEntryDesc12]
Meter = String
MeterStyle = styleFeedReaderEntryDescription
LeftMouseUpAction = #ShowEntry12#

[meterFeedReaderEntry12]
Meter = Image
MeterStyle = styleFeedReaderEntryImage
ImageName = #@#Images\Feedreader\apple.jpg
LeftMouseUpAction = #HideEntry12#

[meterFeedReaderEntryTitle12]
Meter = String
MeterStyle = styleFeedReaderEntryTitle
LeftMouseUpAction = #HideEntry12#

