; ==================================================
; Feeds
;
; Links to each Feed is displayed here
; ==================================================
[meterFeedReaderFeed1]
Meter = String
X = 14
Y = 75
W = #FeedReaderNaviContentSeperatorOffset#
H = 16
AntiAlias = 1
Text = Call me Feed

[meterFeedReaderFeed2]
Meter = String
X = 14
Y = 100
W = #FeedReaderNaviContentSeperatorOffset#
H = 16
AntiAlias = 1
Text = Call me Beast