; ==================================================
; Foreground
; ==================================================
; Corner
[meterFeedReaderForegroundCornerTopLeft]
Meter = Roundline
MeterStyle = styleFeedReaderForegroundCorner|styleFeedReaderForegroundCornerTopLeft

[meterFeedReaderForegroundCornerTopRight]
Meter = Roundline
MeterStyle = styleFeedReaderForegroundCorner|styleFeedReaderForegroundCornerTopRight

[meterFeedReaderForegroundCornerBottomLeft]
Meter = Roundline
MeterStyle = styleFeedReaderForegroundCorner|styleFeedReaderForegroundCornerBottomLeft

[meterFeedReaderForegroundCornerBottomRight]
Meter = Roundline
MeterStyle = styleFeedReaderForegroundCorner|styleFeedReaderForegroundCornerBottomRight

; Center
[meterFeedReaderForeground]
Meter = Image
MeterStyle = styleFeedReaderForeground

; Edges
[meterFeedReaderForegroundTop]
Meter = Image
MeterStyle = styleFeedReaderForegroundEdge|styleFeedReaderForegroundEdgeTop

[meterFeedReaderForegroundBottom]
Meter = Image
MeterStyle = styleFeedReaderForegroundEdge|styleFeedReaderForegroundEdgeBottom

[meterFeedReaderForegroundLeft]
Meter = Image
MeterStyle = styleFeedReaderForegroundEdge|styleFeedReaderForegroundEdgeLeft

[meterFeedReaderForegroundRight]
Meter = Image
MeterStyle = styleFeedReaderForegroundEdge|styleFeedReaderForegroundEdgeRight