; ==================================================
; Foreground
; ==================================================
; Corner
[iForegroundCornerTopLeft]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerTopLeft

[iForegroundCornerTopRight]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerTopRight

[iForegroundCornerBottomLeft]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerBottomLeft

[iForegroundCornerBottomRight]
Meter = Roundline
MeterStyle = yForegroundCorner|yForegroundCornerBottomRight

; Center
[iForeground]
Meter = Image
MeterStyle = yForeground

; Edges
[iForegroundTop]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeTop

[iForegroundBottom]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeBottom

[iForegroundLeft]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeLeft

[iForegroundRight]
Meter = Image
MeterStyle = yForegroundEdge|yForegroundEdgeRight