; Top
; ==================================================
[iBackgroundTL]
Meter = Roundline
MeterStyle = yBackgroundCorner | yBackgroundTL

[iBackgroundT]
Meter = Image
MeterStyle = yBackgroundEdge | yBackgroundT

[iBackgroundTR]
Meter = Roundline
MeterStyle = yBackgroundCorner | yBackgroundTR

; Center
; ==================================================
[iBackgroundL]
Meter = Image
MeterStyle = yBackgroundEdge | yBackgroundL

[iBackground]
Meter = Image
MeterStyle = yBackground

[iBackgroundR]
Meter = Image
MeterStyle = yBackgroundEdge | yBackgroundR

; Bottom
; ==================================================
[iBackgroundBL]
Meter = Roundline
MeterStyle = yBackgroundCorner | yBackgroundBL

[iBackgroundB]
Meter = Image
MeterStyle = yBackgroundEdge | yBackgroundB

[iBackgroundBR]
Meter = Roundline
MeterStyle = yBackgroundCorner | yBackgroundBR