; ==================================================
; ScrollBar
;
; indicating how many feeds are in that category
; and enables you to scroll within
; ==================================================
; Up
[sScrollbarArrowUp]
Meter = String
MeterStyle = yScrollBarArrows
Y = 70
Text = "5"

; Down
[sScrollbarArrowDown]
Meter = String
Y = 800
AntiAlias = 1
Text = "6"

; Area
[meterFeedReaderScrollbarBar]
Meter = Image
MeterStyle = yScrollBarArea