; ==================================================
; Search
;
; enables you to search within your feeds 
; after certain things
; ==================================================
; Seperator
[meterFeedReaderNaviSearchSeperator]
Meter = Image
MeterStyle = styleFeedReaderNaviSearchSeperator

; Search Field
[meterFeedReaderNaviSearchField]
Meter = String
MeterStyle = styleFeedReaderNaviSearchField

; Icon
[meterFeedReaderNaviSearchButtonBackground]
Meter = Image
MeterStyle = styleFeedReaderNaviSearchButtonBackground

[meterFeedReaderNaviSearchButton]
Meter = Image
MeterStyle = styleFeedReaderNaviSearchButton
