; BarDummy
[iBarDummy]
Meter = Image
MeterStyle = yBarDummy

; Meter Progressbar
[iBarMouseInteraction1]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction2]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction3]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction4]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction5]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction6]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction7]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction8]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction9]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction10]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction11]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction12]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction13]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction14]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction15]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction16]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction17]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction18]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction19]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction20]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction21]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction22]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction23]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction24]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction25]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction26]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction27]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction28]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction29]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction30]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction31]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction32]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction33]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction34]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction35]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction36]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction37]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction38]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction39]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction40]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction41]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction42]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction43]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction44]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction45]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction46]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction47]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction48]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction49]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction50]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction51]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction52]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction53]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction54]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction55]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction56]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction57]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction58]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction59]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction60]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction61]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction62]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction63]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction64]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction65]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction66]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction67]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction68]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction69]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction70]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction71]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction72]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction73]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction74]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction75]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction76]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction77]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction78]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction79]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction80]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction81]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction82]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction83]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction84]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction85]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction86]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction87]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction88]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction89]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction90]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction91]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction92]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction93]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction94]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction95]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction96]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction97]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction98]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction99]
Meter = Image
MeterStyle = yBarMouseInteraction

[iBarMouseInteraction100]
Meter = Image
MeterStyle = yBarMouseInteraction

