[mD1Date]
Meter = String
MeterStyle = sDateDefault
Text = Loading

; Background
; ==================================================
; Meter Background Top Left
[mD1Seperator]
Meter = Image
MeterStyle = sSeperator

; Meter Dummy
[mD1Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD1E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD1E1Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 2
; =========
; Meter Element Bar
[mD1E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E2Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 3
; =========
; Meter Element Bar
[mD1E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E3Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 4
; =========
; Meter Element Bar
[mD1E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E4Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 5
; =========
; Meter Element Bar
[mD1E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E5Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 6
; =========
; Meter Element Bar
[mD1E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E6Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 7
; =========
; Meter Element Bar
[mD1E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E7Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 8
; =========
; Meter Element Bar
[mD1E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD1E8Info]
Meter = String
MeterStyle = sEInfoDefault