[mD9Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD9Seperator]
Meter = Image
MeterStyle = sSeperator

; Meter Dummy
[mD9Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD9E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD9E1Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 2
; =========
; Meter Element Bar
[mD9E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E2Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 3
; =========
; Meter Element Bar
[mD9E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E3Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 4
; =========
; Meter Element Bar
[mD9E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E4Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 5
; =========
; Meter Element Bar
[mD9E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E5Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 6
; =========
; Meter Element Bar
[mD9E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E6Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 7
; =========
; Meter Element Bar
[mD9E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E7Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 8
; =========
; Meter Element Bar
[mD9E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD9E8Info]
Meter = String
MeterStyle = sEInfoDefault