[Variables]
DayWidth = 250
DaySpacing = 9

; Work Maike
Cal1 = https://www.google.com/calendar/feeds/7ibhtmaefappftac00g2702j68%40group.calendar.google.com/private-88ffef7aeb85fdfc246fa140414004c9/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a

; Privat Maike
Cal2 = https://www.google.com/calendar/feeds/maikefiege%40googlemail.com/private-50bcd20b6cca19dfd3616b6e3618fe12/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a

; Work Do, Tran Minh
Cal3 = https://www.google.com/calendar/feeds/do.tranminh%40googlemail.com/private-e969e3c6590e12c6c2ed3d2643740854/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a

; Privat Do, Tran Minh
Cal4 = https://www.google.com/calendar/feeds/fuuffojqgkid0dmt2j6nrmv73k%40group.calendar.google.com/private-668b8725e481e19a154980ee6902d422/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a


DefaultBarColor = 255,255,255,255
BarColor1 = 25,162,222,255
BarColor2 = 25,162,222,100
BarColor3 = 230,93,33,255
BarColor4 = 230,93,33,100