[Variables]
DayWidth = 250
DaySpacing = 6

Cal1 = https://www.google.com/calendar/feeds/7ibhtmaefappftac00g2702j68%40group.calendar.google.com/private-88ffef7aeb85fdfc246fa140414004c9/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
Cal2 = https://www.google.com/calendar/feeds/maikefiege%40googlemail.com/private-50bcd20b6cca19dfd3616b6e3618fe12/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
Cal3 = https://www.google.com/calendar/feeds/badhard.ba%40googlemail.com/private-d8255c7950dc68519ebb1a5565191e52/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
Cal4 = https://www.google.com/calendar/feeds/hp8m4q16h1fmevv1dum8hjq9dg%40group.calendar.google.com/private-7a0dba09af55de9c31f229e4c773dd9c/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a
Cal5 = https://www.google.com/calendar/feeds/do.tranminh%40googlemail.com/private-e969e3c6590e12c6c2ed3d2643740854/basic?max-results=8&futureevents=true&singleevents=true&orderby=starttime&sortorder=a

BarColor1 = 25,162,222,255
BarColor2 = 25,162,222,100
BarColor3 = 230,93,33,255
BarColor4 = 230,93,33,100
BarColor5 = 255,00,00,255