; Date
; ==================================================
[sDate]
X = (0 + 0)R
Y = 5
FontSize = 9
FontFace = century Gothic
FontColor = FF8800
AntiAlias = 1
;Text = Dienstag, der 13. Feb

; Seperator
; ==================================================
[sSeperator]
X = 0r
Y = 0R
W = #DayWidth#
H = 3
SolidColor = 225,225,225,35

[sDummy] 
X = (0 + 9)r
Y = 0R

; Elements
; ========
[sEBar]
X = (0 - 7)r
Y = (0 + 15)r
W = 3
H = 12
;SolidColor = 0000FF

[sEInfo]
X = (0 + 4)R
Y = (0 - 1)r
W = #DayWidth#
H = 16
FontColor = FFFFFF
SolidColor = 00000001
FontSize = 9
FontFace = century Gothic
AntiAlias = 1
ClipString = 1
;Text = 00:00 das ist ein Test