[styleShortcut]
FontFace = Calibri
Fontsize = 9
FontColor = FFFFFF
StringStyle = Bold
StringEffect = Shadow
FontEffectColor = 0,0,0,40
X = 10R
Y = 0r
AntiAlias = 1

[styleShortcutSeperator]
Text = "|"

[meterShortcut1]
Meter = String
MeterStyle = styleShortcut
Text = Work
LeftMouseUpAction = ["D:/Data/Dropbox/Uni"]
Y = 5
[meterShortcutSeperator1]
Meter = String
MeterStyle = styleShortcut | styleShortcutSeperator

[meterShortcut2]
Meter = String
MeterStyle = styleShortcut
Text = Fun
LeftMouseUpAction = ["D:\Entertainment"]
Postfix = ""