[measureTime]
Measure = Time
Format = %A %H:%M

[measureDate]
Measure = Time
Format = %d %b %Y

[meterTime]
Meter = String
MeasureName = measureTime

FontFace = Calibri
FontSize = 8
StringStyle = Normal
StringAlign = Left
FontColor = FFFFFF
AntiAlias = 1
X = -100 + 0R
Y = 0
W = 100
H = 30

[meterDate]
Meter = String
MeasureName = measureDate

FontFace = Calibri
FontSize = 8
StringStyle = Normal
StringAlign = Left
FontColor = FFFFFF
AntiAlias = 1
X = 0r
Y = 11r
W = 100
H = 30

