[meterDay1Date]
Meter = String
MeterStyle = styleGcalDate

[meterDay1BarDummy]
Meter = Image
MeterStyle = styleGcalBar
X = 0r
Y = 0r
SolidColor = 00000000

[meterDay1EventDummy]
Meter = String
MeterStyle = styleGcalDesc
Text = ""

[meterDay1Bar1]
Meter = Image
MeterStyle = styleGcalBar

[meterDay1Event1]
Meter = String
MeterStyle = styleGcalDesc

[meterDay1Bar2]
Meter = Image
MeterStyle = styleGcalBar

[meterDay1Event2]
Meter = String
MeterStyle = styleGcalDesc

[meterDay1Bar3]
Meter = Image
MeterStyle = styleGcalBar

[meterDay1Event3]
Meter = String
MeterStyle = styleGcalDesc

[meterDay1Bar4]
Meter = Image
MeterStyle = styleGcalBar

[meterDay1Event4]
Meter = String
MeterStyle = styleGcalDesc

[meterDay1DummyReset]
Meter = Image
X = ([meterDay1Date:X] + 250)
Y = [meterDay1Date:Y]
DynamicVariables = 1
;[meterDay1MoreEvents]
;Meter = String
;MeterStyle = styleGcalMoreEvents