[iElementMG12]
Meter = Image
MeterStyle = yMG | yMG12


; Dummy 121
[iDummy121Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 122
[iDummy122Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 124
[iDummy124Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 030
[iElement030Background]
Meter = Image
MeterStyle = yGroupDefault | #Group030#

[sElement030AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber030#

[sElement030Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol030#

[sElement030Name]
Meter = String
MeterStyle = yName
Text = #Name030#

[sElement030AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass030#


; Element 048
[iElement048Background]
Meter = Image
MeterStyle = yGroupDefault | #Group048#

[sElement048AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber048#

[sElement048Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol048#

[sElement048Name]
Meter = String
MeterStyle = yName
Text = #Name048#

[sElement048AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass048#


; Element 080
[iElement080Background]
Meter = Image
MeterStyle = yGroupDefault | #Group080#

[sElement080AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber080#

[sElement080Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol080#

[sElement080Name]
Meter = String
MeterStyle = yName
Text = #Name080#

[sElement080AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass080#


; Element 112
[iElement112Background]
Meter = Image
MeterStyle = yGroupDefault | #Group112#

[sElement112AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber112#

[sElement112Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol112#

[sElement112Name]
Meter = String
MeterStyle = yName
Text = #Name112#

[sElement112AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass112#


; Dummy 128
[iDummy128Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 065
[iElement065Background]
Meter = Image
MeterStyle = yGroupDefault | #Group065#

[sElement065AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber065#

[sElement065Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol065#

[sElement065Name]
Meter = String
MeterStyle = yName
Text = #Name065#

[sElement065AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass065#


; Element 097
[iElement097Background]
Meter = Image
MeterStyle = yGroupDefault | #Group097#

[sElement097AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber097#

[sElement097Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol097#

[sElement097Name]
Meter = String
MeterStyle = yName
Text = #Name097#

[sElement097AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass097#

