[iElementMG18]
Meter = Image
MeterStyle = yMG | yMG18


; Element 002
[iElement002Background]
Meter = Image
MeterStyle = yGroupDefault | #Group002#

[sElement002AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber002#

[sElement002Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol002#

[sElement002Name]
Meter = String
MeterStyle = yName
Text = #Name002#

[sElement002AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass002#


; Element 010
[iElement010Background]
Meter = Image
MeterStyle = yGroupDefault | #Group010#

[sElement010AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber010#

[sElement010Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol010#

[sElement010Name]
Meter = String
MeterStyle = yName
Text = #Name010#

[sElement010AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass010#


; Element 018
[iElement018Background]
Meter = Image
MeterStyle = yGroupDefault | #Group018#

[sElement018AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber018#

[sElement018Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol018#

[sElement018Name]
Meter = String
MeterStyle = yName
Text = #Name018#

[sElement018AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass018#


; Element 036
[iElement036Background]
Meter = Image
MeterStyle = yGroupDefault | #Group036#

[sElement036AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber036#

[sElement036Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol036#

[sElement036Name]
Meter = String
MeterStyle = yName
Text = #Name036#

[sElement036AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass036#


; Element 054
[iElement054Background]
Meter = Image
MeterStyle = yGroupDefault | #Group054#

[sElement054AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber054#

[sElement054Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol054#

[sElement054Name]
Meter = String
MeterStyle = yName
Text = #Name054#

[sElement054AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass054#


; Element 086 
[iElement086Background]
Meter = Image
MeterStyle = yGroupDefault | #Group086#

[sElement086AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber086#

[sElement086Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol086#

[sElement086Name]
Meter = String
MeterStyle = yName
Text = #Name086#

[sElement086AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass086#


; Element 118
[iElement118Background]
Meter = Image
MeterStyle = yGroupDefault | #Group118#

[sElement118AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber118#

[sElement118Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol118#

[sElement118Name]
Meter = String
MeterStyle = yName
Text = #Name118#

[sElement118AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass118#


; Dummy 188
[iDummy188Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 071
[iElement071Background]
Meter = Image
MeterStyle = yGroupDefault | #Group071#

[sElement071AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber071#

[sElement071Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol071#

[sElement071Name]
Meter = String
MeterStyle = yName
Text = #Name071#

[sElement071AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass071#


; Element 103
[iElement103Background]
Meter = Image
MeterStyle = yGroupDefault | #Group103#

[sElement103AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber103#

[sElement103Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol103#

[sElement103Name]
Meter = String
MeterStyle = yName
Text = #Name103#

[sElement103AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass103#

