[iElementMG06]
Meter = Image
MeterStyle = yMG | yMG06


; Dummy 061
[iDummy061Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 062
[iDummy062Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 063
[iDummy063Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 024
[iElement024Background]
Meter = Image
MeterStyle = yGroupDefault | #Group024#

[sElement024AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber024#

[sElement024Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol024#

[sElement024Name]
Meter = String
MeterStyle = yName
Text = #Name024#

[sElement024AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass024#


; Element 042
[iElement042Background]
Meter = Image
MeterStyle = yGroupDefault | #Group042#

[sElement042AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber042#

[sElement042Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol042#

[sElement042Name]
Meter = String
MeterStyle = yName
Text = #Name042#

[sElement042AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass042#


; Element 074
[iElement074Background]
Meter = Image
MeterStyle = yGroupDefault | #Group074#

[sElement074AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber074#

[sElement074Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol074#

[sElement074Name]
Meter = String
MeterStyle = yName
Text = #Name074#

[sElement074AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass074#


; Element 106
[iElement106Background]
Meter = Image
MeterStyle = yGroupDefault | #Group106#

[sElement106AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber106#

[sElement106Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol106#

[sElement106Name]
Meter = String
MeterStyle = yName
Text = #Name106#

[sElement106AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass106#


; Dummy 068
[iDummy068Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 059
[iElement059Background]
Meter = Image
MeterStyle = yGroupDefault | #Group059#

[sElement059AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber059#

[sElement059Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol059#

[sElement059Name]
Meter = String
MeterStyle = yName
Text = #Name059#

[sElement059AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass059#


; Element 091
[iElement091Background]
Meter = Image
MeterStyle = yGroupDefault | #Group091#

[sElement091AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber091#

[sElement091Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol091#

[sElement091Name]
Meter = String
MeterStyle = yName
Text = #Name091#

[sElement091AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass091#

