; Element 001
[iElement001Background]
Meter = Image
MeterStyle = yGroupDefault | #Group001#

[sElement001AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber001#

[sElement001Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol001#

[sElement001Name]
Meter = String
MeterStyle = yName
Text = #Name001#

[sElement001AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass001#


; Element 003
[iElement003Background]
Meter = Image
MeterStyle = yGroupDefault | #Group003#

[sElement003AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber003#

[sElement003Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol003#

[sElement003Name]
Meter = String
MeterStyle = yName
Text = #Name003#

[sElement003AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass003#


; Element 011
[iElement011Background]
Meter = Image
MeterStyle = yGroupDefault | #Group011#

[sElement011AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber011#

[sElement011Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol011#

[sElement011Name]
Meter = String
MeterStyle = yName
Text = #Name011#

[sElement011AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass011#


; Element 019
[iElement019Background]
Meter = Image
MeterStyle = yGroupDefault | #Group019#

[sElement019AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber019#

[sElement019Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol019#

[sElement019Name]
Meter = String
MeterStyle = yName
Text = #Name019#

[sElement019AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass019#


; Element 037
[iElement037Background]
Meter = Image
MeterStyle = yGroupDefault | #Group037#

[sElement037AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber037#

[sElement037Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol037#

[sElement037Name]
Meter = String
MeterStyle = yName
Text = #Name037#

[sElement037AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass037#


; Element 055
[iElement055Background]
Meter = Image
MeterStyle = yGroupDefault | #Group055#

[sElement055AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber055#

[sElement055Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol055#

[sElement055Name]
Meter = String
MeterStyle = yName
Text = #Name055#

[sElement055AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass055#


; Element 087
[iElement087Background]
Meter = Image
MeterStyle = yGroupDefault | #Group087#

[sElement087AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber087#

[sElement087Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol087#

[sElement087Name]
Meter = String
MeterStyle = yName
Text = #Name087#

[sElement087AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass087#


