[iElementMG14]
Meter = Image
MeterStyle = yMG | yMG14


; Dummy 141
[iDummy141Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 006
[iElement006Background]
Meter = Image
MeterStyle = yGroupDefault | #Group006#

[sElement006AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber006#

[sElement006Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol006#

[sElement006Name]
Meter = String
MeterStyle = yName
Text = #Name006#

[sElement006AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass006#


; Element 014
[iElement014Background]
Meter = Image
MeterStyle = yGroupDefault | #Group014#

[sElement014AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber014#

[sElement014Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol014#

[sElement014Name]
Meter = String
MeterStyle = yName
Text = #Name014#

[sElement014AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass014#


; Element 032
[iElement032Background]
Meter = Image
MeterStyle = yGroupDefault | #Group032#

[sElement032AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber032#

[sElement032Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol032#

[sElement032Name]
Meter = String
MeterStyle = yName
Text = #Name032#

[sElement032AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass032#


; Element 050
[iElement050Background]
Meter = Image
MeterStyle = yGroupDefault | #Group050#

[sElement050AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber050#

[sElement050Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol050#

[sElement050Name]
Meter = String
MeterStyle = yName
Text = #Name050#

[sElement050AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass050#


; Element 082 
[iElement082Background]
Meter = Image
MeterStyle = yGroupDefault | #Group082#

[sElement082AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber082#

[sElement082Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol082#

[sElement082Name]
Meter = String
MeterStyle = yName
Text = #Name082#

[sElement082AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass082#


; Element 114
[iElement114Background]
Meter = Image
MeterStyle = yGroupDefault | #Group114#

[sElement114AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber114#

[sElement114Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol114#

[sElement114Name]
Meter = String
MeterStyle = yName
Text = #Name114#

[sElement114AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass114#


; Dummy 148
[iDummy148Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 067
[iElement067Background]
Meter = Image
MeterStyle = yGroupDefault | #Group067#

[sElement067AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber067#

[sElement067Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol067#

[sElement067Name]
Meter = String
MeterStyle = yName
Text = #Name067#

[sElement067AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass067#


; Element 099
[iElement099Background]
Meter = Image
MeterStyle = yGroupDefault | #Group099#

[sElement099AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber099#

[sElement099Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol099#

[sElement099Name]
Meter = String
MeterStyle = yName
Text = #Name099#

[sElement099AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass099#

