[iElementMG15]
Meter = Image
MeterStyle = yMG | yMG15


; Dummy 151
[iDummy151Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 007
[iElement007Background]
Meter = Image
MeterStyle = yGroupDefault | #Group007#

[sElement007AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber007#

[sElement007Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol007#

[sElement007Name]
Meter = String
MeterStyle = yName
Text = #Name007#

[sElement007AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass007#


; Element 015
[iElement015Background]
Meter = Image
MeterStyle = yGroupDefault | #Group015#

[sElement015AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber015#

[sElement015Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol015#

[sElement015Name]
Meter = String
MeterStyle = yName
Text = #Name015#

[sElement015AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass015#


; Element 033
[iElement033Background]
Meter = Image
MeterStyle = yGroupDefault | #Group033#

[sElement033AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber033#

[sElement033Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol033#

[sElement033Name]
Meter = String
MeterStyle = yName
Text = #Name033#

[sElement033AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass033#


; Element 051
[iElement051Background]
Meter = Image
MeterStyle = yGroupDefault | #Group051#

[sElement051AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber051#

[sElement051Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol051#

[sElement051Name]
Meter = String
MeterStyle = yName
Text = #Name051#

[sElement051AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass051#


; Element 083 
[iElement083Background]
Meter = Image
MeterStyle = yGroupDefault | #Group083#

[sElement083AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber083#

[sElement083Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol083#

[sElement083Name]
Meter = String
MeterStyle = yName
Text = #Name083#

[sElement083AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass083#


; Element 115
[iElement115Background]
Meter = Image
MeterStyle = yGroupDefault | #Group115#

[sElement115AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber115#

[sElement115Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol115#

[sElement115Name]
Meter = String
MeterStyle = yName
Text = #Name115#

[sElement115AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass115#


; Dummy 158
[iDummy158Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 068
[iElement068Background]
Meter = Image
MeterStyle = yGroupDefault | #Group068#

[sElement068AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber068#

[sElement068Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol068#

[sElement068Name]
Meter = String
MeterStyle = yName
Text = #Name068#

[sElement068AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass068#


; Element 100
[iElement100Background]
Meter = Image
MeterStyle = yGroupDefault | #Group100#

[sElement100AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber100#

[sElement100Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol100#

[sElement100Name]
Meter = String
MeterStyle = yName
Text = #Name100#

[sElement100AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass100#

