[iElementMG09]
Meter = Image
MeterStyle = yMG | yMG09


; Dummy 091
[iDummy091Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 092
[iDummy092Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 094
[iDummy094Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 027
[iElement027Background]
Meter = Image
MeterStyle = yGroupDefault | #Group027#

[sElement027AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber027#

[sElement027Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol027#

[sElement027Name]
Meter = String
MeterStyle = yName
Text = #Name027#

[sElement027AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass027#


; Element 045
[iElement045Background]
Meter = Image
MeterStyle = yGroupDefault | #Group045#

[sElement045AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber045#

[sElement045Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol045#

[sElement045Name]
Meter = String
MeterStyle = yName
Text = #Name045#

[sElement045AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass045#


; Element 077
[iElement077Background]
Meter = Image
MeterStyle = yGroupDefault | #Group077#

[sElement077AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber077#

[sElement077Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol077#

[sElement077Name]
Meter = String
MeterStyle = yName
Text = #Name077#

[sElement077AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass077#


; Element 109
[iElement109Background]
Meter = Image
MeterStyle = yGroupDefault | #Group109#

[sElement109AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber109#

[sElement109Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol109#

[sElement109Name]
Meter = String
MeterStyle = yName
Text = #Name109#

[sElement109AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass109#


; Dummy 098
[iDummy098Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 062
[iElement062Background]
Meter = Image
MeterStyle = yGroupDefault | #Group062#

[sElement062AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber062#

[sElement062Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol062#

[sElement062Name]
Meter = String
MeterStyle = yName
Text = #Name062#

[sElement062AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass062#


; Element 094
[iElement094Background]
Meter = Image
MeterStyle = yGroupDefault | #Group094#

[sElement094AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber094#

[sElement094Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol094#

[sElement094Name]
Meter = String
MeterStyle = yName
Text = #Name094#

[sElement094AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass094#

