[iElementMG04]
Meter = Image
MeterStyle = yMG | yMG04


; Dummy 041
[iDummy041Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 042
[iDummy042Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 043
[iDummy043Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 022
[iElement022Background]
Meter = Image
MeterStyle = yGroupDefault | #Group022#

[sElement022AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber022#

[sElement022Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol022#

[sElement022Name]
Meter = String
MeterStyle = yName
Text = #Name022#

[sElement022AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass022#


; Element 040
[iElement040Background]
Meter = Image
MeterStyle = yGroupDefault | #Group040#

[sElement040AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber040#

[sElement040Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol040#

[sElement040Name]
Meter = String
MeterStyle = yName
Text = #Name040#

[sElement040AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass040#


; Element 072
[iElement072Background]
Meter = Image
MeterStyle = yGroupDefault | #Group072#

[sElement072AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber072#

[sElement072Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol072#

[sElement072Name]
Meter = String
MeterStyle = yName
Text = #Name072#

[sElement072AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass072#


; Element 104
[iElement104Background]
Meter = Image
MeterStyle = yGroupDefault | #Group104#

[sElement104AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber104#

[sElement104Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol104#

[sElement104Name]
Meter = String
MeterStyle = yName
Text = #Name104#

[sElement104AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass104#


; Dummy 048
[iDummy048Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 057
[iElement057Background]
Meter = Image
MeterStyle = yGroupDefault | #Group057#

[sElement057AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber057#

[sElement057Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol057#

[sElement057Name]
Meter = String
MeterStyle = yName
Text = #Name057#

[sElement057AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass057#


; Element 089
[iElement089Background]
Meter = Image
MeterStyle = yGroupDefault | #Group089#

[sElement089AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber089#

[sElement089Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol089#

[sElement089Name]
Meter = String
MeterStyle = yName
Text = #Name089#

[sElement089AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass089#

