[iElementMG05]
Meter = Image
MeterStyle = yMG | yMG05


; Dummy 051
[iDummy051Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 052
[iDummy052Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 053
[iDummy053Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 023
[iElement023Background]
Meter = Image
MeterStyle = yGroupDefault | #Group023#

[sElement023AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber023#

[sElement023Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol023#

[sElement023Name]
Meter = String
MeterStyle = yName
Text = #Name023#

[sElement023AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass023#


; Element 041
[iElement041Background]
Meter = Image
MeterStyle = yGroupDefault | #Group041#

[sElement041AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber041#

[sElement041Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol041#

[sElement041Name]
Meter = String
MeterStyle = yName
Text = #Name041#

[sElement041AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass041#


; Element 073
[iElement073Background]
Meter = Image
MeterStyle = yGroupDefault | #Group073#

[sElement073AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber073#

[sElement073Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol073#

[sElement073Name]
Meter = String
MeterStyle = yName
Text = #Name073#

[sElement073AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass073#


; Element 105
[iElement105Background]
Meter = Image
MeterStyle = yGroupDefault | #Group105#

[sElement105AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber105#

[sElement105Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol105#

[sElement105Name]
Meter = String
MeterStyle = yName
Text = #Name105#

[sElement105AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass105#


; Dummy 058
[iDummy058Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 058
[iElement058Background]
Meter = Image
MeterStyle = yGroupDefault | #Group058#

[sElement058AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber058#

[sElement058Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol058#

[sElement058Name]
Meter = String
MeterStyle = yName
Text = #Name058#

[sElement058AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass058#


; Element 090
[iElement090Background]
Meter = Image
MeterStyle = yGroupDefault | #Group090#

[sElement090AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber090#

[sElement090Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol090#

[sElement090Name]
Meter = String
MeterStyle = yName
Text = #Name090#

[sElement090AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass090#

