[iElementMG16]
Meter = Image
MeterStyle = yMG | yMG16


; Dummy 161
[iDummy161Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 008
[iElement008Background]
Meter = Image
MeterStyle = yGroupDefault | #Group008#

[sElement008AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber008#

[sElement008Symbol]
Meter = String
MeterStyle = ySymbol | yStateGas
Text = #Symbol008#

[sElement008Name]
Meter = String
MeterStyle = yName
Text = #Name008#

[sElement008AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass008#


; Element 016
[iElement016Background]
Meter = Image
MeterStyle = yGroupDefault | #Group016#

[sElement016AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber016#

[sElement016Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol016#

[sElement016Name]
Meter = String
MeterStyle = yName
Text = #Name016#

[sElement016AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass016#


; Element 034
[iElement034Background]
Meter = Image
MeterStyle = yGroupDefault | #Group034#

[sElement034AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber034#

[sElement034Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol034#

[sElement034Name]
Meter = String
MeterStyle = yName
Text = #Name034#

[sElement034AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass034#


; Element 052
[iElement052Background]
Meter = Image
MeterStyle = yGroupDefault | #Group052#

[sElement052AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber052#

[sElement052Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol052#

[sElement052Name]
Meter = String
MeterStyle = yName
Text = #Name052#

[sElement052AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass052#


; Element 084 
[iElement084Background]
Meter = Image
MeterStyle = yGroupDefault | #Group084#

[sElement084AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber084#

[sElement084Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol084#

[sElement084Name]
Meter = String
MeterStyle = yName
Text = #Name084#

[sElement084AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass084#


; Element 116
[iElement116Background]
Meter = Image
MeterStyle = yGroupDefault | #Group116#

[sElement116AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber116#

[sElement116Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol116#

[sElement116Name]
Meter = String
MeterStyle = yName
Text = #Name116#

[sElement116AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass116#


; Dummy 168
[iDummy168Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 069
[iElement069Background]
Meter = Image
MeterStyle = yGroupDefault | #Group069#

[sElement069AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber069#

[sElement069Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol069#

[sElement069Name]
Meter = String
MeterStyle = yName
Text = #Name069#

[sElement069AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass069#


; Element 101
[iElement101Background]
Meter = Image
MeterStyle = yGroupDefault | #Group101#

[sElement101AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber101#

[sElement101Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol101#

[sElement101Name]
Meter = String
MeterStyle = yName
Text = #Name101#

[sElement101AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass101#

