[iElementMG07]
Meter = Image
MeterStyle = yMG | yMG07


; Dummy 071
[iDummy071Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 072
[iDummy072Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 073
[iDummy073Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 025
[iElement025Background]
Meter = Image
MeterStyle = yGroupDefault | #Group025#

[sElement025AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber025#

[sElement025Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol025#

[sElement025Name]
Meter = String
MeterStyle = yName
Text = #Name025#

[sElement025AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass025#


; Element 043
[iElement043Background]
Meter = Image
MeterStyle = yGroupDefault | #Group043#

[sElement043AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber043#

[sElement043Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol043#

[sElement043Name]
Meter = String
MeterStyle = yName
Text = #Name043#

[sElement043AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass043#


; Element 075
[iElement075Background]
Meter = Image
MeterStyle = yGroupDefault | #Group075#

[sElement075AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber075#

[sElement075Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol075#

[sElement075Name]
Meter = String
MeterStyle = yName
Text = #Name075#

[sElement075AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass075#


; Element 107
[iElement107Background]
Meter = Image
MeterStyle = yGroupDefault | #Group107#

[sElement107AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber107#

[sElement107Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol107#

[sElement107Name]
Meter = String
MeterStyle = yName
Text = #Name107#

[sElement107AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass107#


; Dummy 078
[iDummy078Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 060
[iElement060Background]
Meter = Image
MeterStyle = yGroupDefault | #Group060#

[sElement060AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber060#

[sElement060Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol060#

[sElement060Name]
Meter = String
MeterStyle = yName
Text = #Name060#

[sElement060AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass060#


; Element 092
[iElement092Background]
Meter = Image
MeterStyle = yGroupDefault | #Group092#

[sElement092AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber092#

[sElement092Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol092#

[sElement092Name]
Meter = String
MeterStyle = yName
Text = #Name092#

[sElement092AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass092#

