[iElementMG11]
Meter = Image
MeterStyle = yMG | yMG11


; Dummy 111
[iDummy111Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 112
[iDummy112Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 114
[iDummy114Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 029
[iElement029Background]
Meter = Image
MeterStyle = yGroupDefault | #Group029#

[sElement029AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber029#

[sElement029Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol029#

[sElement029Name]
Meter = String
MeterStyle = yName
Text = #Name029#

[sElement029AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass029#


; Element 047
[iElement047Background]
Meter = Image
MeterStyle = yGroupDefault | #Group047#

[sElement047AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber047#

[sElement047Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol047#

[sElement047Name]
Meter = String
MeterStyle = yName
Text = #Name047#

[sElement047AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass047#


; Element 079
[iElement079Background]
Meter = Image
MeterStyle = yGroupDefault | #Group079#

[sElement079AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber079#

[sElement079Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol079#

[sElement079Name]
Meter = String
MeterStyle = yName
Text = #Name079#

[sElement079AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass079#


; Element 111
[iElement111Background]
Meter = Image
MeterStyle = yGroupDefault | #Group111#

[sElement111AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber111#

[sElement111Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol111#

[sElement111Name]
Meter = String
MeterStyle = yName
Text = #Name111#

[sElement111AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass111#


; Dummy 118
[iDummy118Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 064
[iElement064Background]
Meter = Image
MeterStyle = yGroupDefault | #Group064#

[sElement064AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber064#

[sElement064Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol064#

[sElement064Name]
Meter = String
MeterStyle = yName
Text = #Name064#

[sElement064AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass064#


; Element 096
[iElement096Background]
Meter = Image
MeterStyle = yGroupDefault | #Group096#

[sElement096AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber096#

[sElement096Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol096#

[sElement096Name]
Meter = String
MeterStyle = yName
Text = #Name096#

[sElement096AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass096#

