[iElementMG08]
Meter = Image
MeterStyle = yMG | yMG08


; Dummy 081
[iDummy081Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 082
[iDummy082Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 083
[iDummy083Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 026
[iElement026Background]
Meter = Image
MeterStyle = yGroupDefault | #Group026#

[sElement026AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber026#

[sElement026Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol026#

[sElement026Name]
Meter = String
MeterStyle = yName
Text = #Name026#

[sElement026AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass026#


; Element 044
[iElement044Background]
Meter = Image
MeterStyle = yGroupDefault | #Group044#

[sElement044AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber044#

[sElement044Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol044#

[sElement044Name]
Meter = String
MeterStyle = yName
Text = #Name044#

[sElement044AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass044#


; Element 076
[iElement076Background]
Meter = Image
MeterStyle = yGroupDefault | #Group076#

[sElement076AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber076#

[sElement076Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol076#

[sElement076Name]
Meter = String
MeterStyle = yName
Text = #Name076#

[sElement076AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass076#


; Element 108
[iElement108Background]
Meter = Image
MeterStyle = yGroupDefault | #Group108#

[sElement108AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber108#

[sElement108Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol108#

[sElement108Name]
Meter = String
MeterStyle = yName
Text = #Name108#

[sElement108AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass108#


; Dummy 088
[iDummy088Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 061
[iElement061Background]
Meter = Image
MeterStyle = yGroupDefault | #Group061#

[sElement061AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber061#

[sElement061Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol061#

[sElement061Name]
Meter = String
MeterStyle = yName
Text = #Name061#

[sElement061AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass061#


; Element 093
[iElement093Background]
Meter = Image
MeterStyle = yGroupDefault | #Group093#

[sElement093AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber093#

[sElement093Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol093#

[sElement093Name]
Meter = String
MeterStyle = yName
Text = #Name093#

[sElement093AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass093#

