[iElementMG10]
Meter = Image
MeterStyle = yMG | yMG10


; Dummy 101
[iDummy101Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 102
[iDummy102Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

; Dummy 104
[iDummy104Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 028
[iElement028Background]
Meter = Image
MeterStyle = yGroupDefault | #Group028#

[sElement028AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber028#

[sElement028Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol028#

[sElement028Name]
Meter = String
MeterStyle = yName
Text = #Name028#

[sElement028AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass028#


; Element 046
[iElement046Background]
Meter = Image
MeterStyle = yGroupDefault | #Group046#

[sElement046AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber046#

[sElement046Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol046#

[sElement046Name]
Meter = String
MeterStyle = yName
Text = #Name046#

[sElement046AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass046#


; Element 078
[iElement078Background]
Meter = Image
MeterStyle = yGroupDefault | #Group078#

[sElement078AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber078#

[sElement078Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol078#

[sElement078Name]
Meter = String
MeterStyle = yName
Text = #Name078#

[sElement078AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass078#


; Element 110
[iElement110Background]
Meter = Image
MeterStyle = yGroupDefault | #Group110#

[sElement110AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber110#

[sElement110Symbol]
Meter = String
MeterStyle = ySymbol | yStateSynthetic
Text = #Symbol110#

[sElement110Name]
Meter = String
MeterStyle = yName
Text = #Name110#

[sElement110AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass110#


; Dummy 108
[iDummy108Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 063
[iElement063Background]
Meter = Image
MeterStyle = yGroupDefault | #Group063#

[sElement063AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber063#

[sElement063Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol063#

[sElement063Name]
Meter = String
MeterStyle = yName
Text = #Name063#

[sElement063AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass063#


; Element 095
[iElement095Background]
Meter = Image
MeterStyle = yGroupDefault | #Group095#

[sElement095AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber095#

[sElement095Symbol]
Meter = String
MeterStyle = ySymbol | yStateSolid
Text = #Symbol095#

[sElement095Name]
Meter = String
MeterStyle = yName
Text = #Name095#

[sElement095AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass095#

