[iElementMG02]
Meter = Image
MeterStyle = yMG | yMG02


; Dummy 021
[iDummy021Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy

[sDummy021AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber

[sDummy021Symbol]
Meter = String
MeterStyle = ySymbol

[sDummy021Name]
Meter = String
MeterStyle = yName

[sDummy021AtomicMass]
Meter = String
MeterStyle = yAtomicMass


; Element 004
[iElement004Background]
Meter = Image
MeterStyle = yGroupDefault | #Group004#

[sElement004AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber004#

[sElement004Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol004#

[sElement004Name]
Meter = String
MeterStyle = yName
Text = #Name004#

[sElement004AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass004#


; Element 012
[iElement012Background]
Meter = Image
MeterStyle = yGroupDefault | #Group012#

[sElement012AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber012#

[sElement012Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol012#

[sElement012Name]
Meter = String
MeterStyle = yName
Text = #Name012#

[sElement012AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass012#


; Element 020
[iElement020Background]
Meter = Image
MeterStyle = yGroupDefault | #Group020#

[sElement020AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber020#

[sElement020Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol020#

[sElement020Name]
Meter = String
MeterStyle = yName
Text = #Name020#

[sElement020AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass020#


; Element 038
[iElement038Background]
Meter = Image
MeterStyle = yGroupDefault | #Group038#

[sElement038AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber038#

[sElement038Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol038#

[sElement038Name]
Meter = String
MeterStyle = yName
Text = #Name038#

[sElement038AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass038#


; Element 056
[iElement056Background]
Meter = Image
MeterStyle = yGroupDefault | #Group056#

[sElement056AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber056#

[sElement056Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol056#

[sElement056Name]
Meter = String
MeterStyle = yName
Text = #Name056#

[sElement056AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass056#


; Element 088
[iElement088Background]
Meter = Image
MeterStyle = yGroupDefault | #Group088#

[sElement088AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber088#

[sElement088Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol088#

[sElement088Name]
Meter = String
MeterStyle = yName
Text = #Name088#

[sElement088AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass088#


