[iElementMG03]
Meter = Image
MeterStyle = yMG | yMG03


; Dummy 031
[iDummy031Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Dummy 032
[iDummy032Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Dummy 033
[iDummy033Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 021
[iElement021Background]
Meter = Image
MeterStyle = yGroupDefault | #Group021#

[sElement021AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber021#

[sElement021Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol021#

[sElement021Name]
Meter = String
MeterStyle = yName
Text = #Name021#

[sElement021AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass021#


; Element 039
[iElement039Background]
Meter = Image
MeterStyle = yGroupDefault | #Group039#

[sElement039AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber039#

[sElement039Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol039#

[sElement039Name]
Meter = String
MeterStyle = yName
Text = #Name039#

[sElement039AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass039#


;; Element 020
;[iElement020Background]
;Meter = Image
;MeterStyle = yGroupDefault | #Group020#

;[sElement020AtomicNumber]
;Meter = String
;MeterStyle = yAtomicNumber
;Text = #AtomicNumber020#

;[sElement020Symbol]
;Meter = String
;MeterStyle = ySymbol
;Text = #Symbol020#

;[sElement020Name]
;Meter = String
;MeterStyle = yName
;Text = #Name020#

;[sElement020AtomicMass]
;Meter = String
;MeterStyle = yAtomicMass
;Text = #Mass020#


;; Element 038
;[iElement038Background]
;Meter = Image
;MeterStyle = yGroupDefault | #Group038#

;[sElement038AtomicNumber]
;Meter = String
;MeterStyle = yAtomicNumber
;Text = #AtomicNumber038#

;[sElement038Symbol]
;Meter = String
;MeterStyle = ySymbol
;Text = #Symbol038#

;[sElement038Name]
;Meter = String
;MeterStyle = yName
;Text = #Name038#

;[sElement038AtomicMass]
;Meter = String
;MeterStyle = yAtomicMass
;Text = #Mass038#

