[iElementMG13]
Meter = Image
MeterStyle = yMG | yMG13


; Dummy 131
[iDummy131Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 005
[iElement005Background]
Meter = Image
MeterStyle = yGroupDefault | #Group005#

[sElement005AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber005#

[sElement005Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol005#

[sElement005Name]
Meter = String
MeterStyle = yName
Text = #Name005#

[sElement005AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass005#


; Element 013
[iElement013Background]
Meter = Image
MeterStyle = yGroupDefault | #Group013#

[sElement013AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber013#

[sElement013Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol013#

[sElement013Name]
Meter = String
MeterStyle = yName
Text = #Name013#

[sElement013AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass013#


; Element 031
[iElement031Background]
Meter = Image
MeterStyle = yGroupDefault | #Group031#

[sElement031AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber031#

[sElement031Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol031#

[sElement031Name]
Meter = String
MeterStyle = yName
Text = #Name031#

[sElement031AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass031#


; Element 049
[iElement049Background]
Meter = Image
MeterStyle = yGroupDefault | #Group049#

[sElement049AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber049#

[sElement049Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol049#

[sElement049Name]
Meter = String
MeterStyle = yName
Text = #Name049#

[sElement049AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass049#


; Element 081 
[iElement081Background]
Meter = Image
MeterStyle = yGroupDefault | #Group081#

[sElement081AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber081#

[sElement081Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol081#

[sElement081Name]
Meter = String
MeterStyle = yName
Text = #Name081#

[sElement081AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass081#


; Element 113
[iElement113Background]
Meter = Image
MeterStyle = yGroupDefault | #Group113#

[sElement113AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber113#

[sElement113Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol113#

[sElement113Name]
Meter = String
MeterStyle = yName
Text = #Name113#

[sElement113AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass113#


; Dummy 138
[iDummy138Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 066
[iElement066Background]
Meter = Image
MeterStyle = yGroupDefault | #Group066#

[sElement066AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber066#

[sElement066Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol066#

[sElement066Name]
Meter = String
MeterStyle = yName
Text = #Name066#

[sElement066AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass066#


; Element 098
[iElement098Background]
Meter = Image
MeterStyle = yGroupDefault | #Group098#

[sElement098AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber098#

[sElement098Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol098#

[sElement098Name]
Meter = String
MeterStyle = yName
Text = #Name098#

[sElement098AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass098#

