[iElementMG17]
Meter = Image
MeterStyle = yMG | yMG17


; Dummy 171
[iDummy171Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 009
[iElement009Background]
Meter = Image
MeterStyle = yGroupDefault | #Group009#

[sElement009AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber009#

[sElement009Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol009#

[sElement009Name]
Meter = String
MeterStyle = yName
Text = #Name009#

[sElement009AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass009#


; Element 017
[iElement017Background]
Meter = Image
MeterStyle = yGroupDefault | #Group017#

[sElement017AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber017#

[sElement017Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol017#

[sElement017Name]
Meter = String
MeterStyle = yName
Text = #Name017#

[sElement017AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass017#


; Element 035
[iElement035Background]
Meter = Image
MeterStyle = yGroupDefault | #Group035#

[sElement035AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber035#

[sElement035Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol035#

[sElement035Name]
Meter = String
MeterStyle = yName
Text = #Name035#

[sElement035AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass035#


; Element 053
[iElement053Background]
Meter = Image
MeterStyle = yGroupDefault | #Group053#

[sElement053AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber053#

[sElement053Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol053#

[sElement053Name]
Meter = String
MeterStyle = yName
Text = #Name053#

[sElement053AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass053#


; Element 085 
[iElement085Background]
Meter = Image
MeterStyle = yGroupDefault | #Group085#

[sElement085AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber085#

[sElement085Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol085#

[sElement085Name]
Meter = String
MeterStyle = yName
Text = #Name085#

[sElement085AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass085#


; Element 117
[iElement117Background]
Meter = Image
MeterStyle = yGroupDefault | #Group117#

[sElement117AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber117#

[sElement117Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol117#

[sElement117Name]
Meter = String
MeterStyle = yName
Text = #Name117#

[sElement117AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass117#


; Dummy 178
[iDummy178Background]
Meter = Image
MeterStyle = yGroupDefault | yGroupDummy


; Element 070
[iElement070Background]
Meter = Image
MeterStyle = yGroupDefault | #Group070#

[sElement070AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber070#

[sElement070Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol070#

[sElement070Name]
Meter = String
MeterStyle = yName
Text = #Name070#

[sElement070AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass070#


; Element 102
[iElement102Background]
Meter = Image
MeterStyle = yGroupDefault | #Group102#

[sElement102AtomicNumber]
Meter = String
MeterStyle = yAtomicNumber
Text = #AtomicNumber102#

[sElement102Symbol]
Meter = String
MeterStyle = ySymbol
Text = #Symbol102#

[sElement102Name]
Meter = String
MeterStyle = yName
Text = #Name102#

[sElement102AtomicMass]
Meter = String
MeterStyle = yAtomicMass
Text = #Mass102#

