; Col 1
[iGroupLegend1Dummy]
Meter = Image
MeterStyle = yMG | yMG06 | yGroupLegendDummy


[iGroupLegendAlkaliMetalsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupAlkaliMetals

[sGroupLegendAlkaliMetalsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Akali Metals

[iGroupLegendMetalloidsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupMetalloids

[sGroupLegendMetalloidsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Metalloids


; Col 2
[iGroupLegend2Dummy]
Meter = Image
MeterStyle = yMG | yMG07 | yGroupLegendDummy


[iGroupLegendAlkaliEarthMetalsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupAlkaliEarthMetals

[sGroupLegendAlkaliEarthMetalsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Akali Earth Metals

[iGroupLegendNonMetalsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupNonMetals

[sGroupLegendNonMetalsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Non Metals


; Col 3
[iGroupLegend3Dummy]
Meter = Image
MeterStyle = yMG | yMG08 | yGroupLegendDummy


[iGroupLegendLanthanoidsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupLanthanoids

[sGroupLegendLanthanoidsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Lantha-noids

[iGroupLegendHalogensBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupHalogen

[sGroupLegendHalogensText]
Meter = String
MeterStyle = yGroupLegendText
Text = Halogens


; Col 4
[iGroupLegend4Dummy]
Meter = Image
MeterStyle = yMG | yMG09 | yGroupLegendDummy


[iGroupLegendActinoidsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupActinoids

[sGroupLegendActinoidsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Actinoids

[iGroupLegendNobleGasesBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupNobleGases

[sGroupLegendNobleGasesText]
Meter = String
MeterStyle = yGroupLegendText
Text = Noble Gases


; Col 5
[iGroupLegend5Dummy]
Meter = Image
MeterStyle = yMG | yMG10 | yGroupLegendDummy

[iGroupLegendTransitionMetalsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupTransitionMetals

[sGroupLegendTransitionMetalsText]
Meter = String
MeterStyle = yGroupLegendText
Text = Transition Metals


; Col 6
[iGroupLegend6Dummy]
Meter = Image
MeterStyle = yMG | yMG11 | yGroupLegendDummy

[iGroupLegendPostTransitionMetalsBackground]
Meter = Image
MeterStyle = yGroupLegendBackground | yGroupPostTransitionMetals

[sGroupLegendPostTransitionMetalsText]
Meter = String
MeterStyle = yGroupLegendText
Text = PostTrans Metals

