[iStateLegendDummy]
Meter = Image
MeterStyle = yMG | yMG04 | yStateLegendDummy


[iStateLegendBackground]
Meter = Image
MeterStyle = yStateLegendBackground

[sStateLegendSolid]
Meter = String
MeterStyle = yStateLegendText | yStateSolid
Text = Solid
Y = 0r

[sStateLegendLiquid]
Meter = String
MeterStyle = yStateLegendText | yStateLiquid
Text = Liquid

[sStateLegendGas]
Meter = String
MeterStyle = yStateLegendText | yStateGas
Text = Gas

[sStateLegendSynthetic]
Meter = String
MeterStyle = yStateLegendText | yStateSynthetic
Text = Synthetic