[mD2Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD2Seperator]
Meter = Image
MeterStyle = sSeperator

; Meter Dummy
[mD2Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD2E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD2E1Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 2
; =========
; Meter Element Bar
[mD2E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E2Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 3
; =========
; Meter Element Bar
[mD2E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E3Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 4
; =========
; Meter Element Bar
[mD2E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E4Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 5
; =========
; Meter Element Bar
[mD2E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E5Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 6
; =========
; Meter Element Bar
[mD2E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E6Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 7
; =========
; Meter Element Bar
[mD2E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E7Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 8
; =========
; Meter Element Bar
[mD2E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD2E8Info]
Meter = String
MeterStyle = sEInfoDefault