[mD3Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD3Seperator]
Meter = Bar
MeterStyle = sSeperator

; Meter Dummy
[mD3Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD3E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD3E1Info]
Meter = String
MeterStyle = sEInfo

; Element 2
; =========
; Meter Element Bar
[mD3E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E2Info]
Meter = String
MeterStyle = sEInfo

; Element 3
; =========
; Meter Element Bar
[mD3E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E3Info]
Meter = String
MeterStyle = sEInfo

; Element 4
; =========
; Meter Element Bar
[mD3E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E4Info]
Meter = String
MeterStyle = sEInfo

; Element 5
; =========
; Meter Element Bar
[mD3E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E5Info]
Meter = String
MeterStyle = sEInfo

; Element 6
; =========
; Meter Element Bar
[mD3E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E6Info]
Meter = String
MeterStyle = sEInfo

; Element 7
; =========
; Meter Element Bar
[mD3E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E7Info]
Meter = String
MeterStyle = sEInfo

; Element 8
; =========
; Meter Element Bar
[mD3E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD3E8Info]
Meter = String
MeterStyle = sEInfo