[mD4Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD4Seperator]
Meter = Bar
MeterStyle = sSeperator

; Meter Dummy
[mD4Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD4E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD4E1Info]
Meter = String
MeterStyle = sEInfo

; Element 2
; =========
; Meter Element Bar
[mD4E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E2Info]
Meter = String
MeterStyle = sEInfo

; Element 3
; =========
; Meter Element Bar
[mD4E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E3Info]
Meter = String
MeterStyle = sEInfo

; Element 4
; =========
; Meter Element Bar
[mD4E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E4Info]
Meter = String
MeterStyle = sEInfo

; Element 5
; =========
; Meter Element Bar
[mD4E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E5Info]
Meter = String
MeterStyle = sEInfo

; Element 6
; =========
; Meter Element Bar
[mD4E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E6Info]
Meter = String
MeterStyle = sEInfo

; Element 7
; =========
; Meter Element Bar
[mD4E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E7Info]
Meter = String
MeterStyle = sEInfo

; Element 8
; =========
; Meter Element Bar
[mD4E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD4E8Info]
Meter = String
MeterStyle = sEInfo