[mD5Date]
Meter = String
MeterStyle = sDate

; Background
; ==================================================
; Meter Background Top Left
[mD5Seperator]
Meter = Image
MeterStyle = sSeperator

; Meter Dummy
[mD5Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD5E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD5E1Info]
Meter = String
MeterStyle = sEInfo

; Element 2
; =========
; Meter Element Bar
[mD5E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E2Info]
Meter = String
MeterStyle = sEInfo

; Element 3
; =========
; Meter Element Bar
[mD5E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E3Info]
Meter = String
MeterStyle = sEInfo

; Element 4
; =========
; Meter Element Bar
[mD5E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E4Info]
Meter = String
MeterStyle = sEInfo

; Element 5
; =========
; Meter Element Bar
[mD5E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E5Info]
Meter = String
MeterStyle = sEInfo

; Element 6
; =========
; Meter Element Bar
[mD5E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E6Info]
Meter = String
MeterStyle = sEInfo

; Element 7
; =========
; Meter Element Bar
[mD5E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E7Info]
Meter = String
MeterStyle = sEInfo

; Element 8
; =========
; Meter Element Bar
[mD5E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD5E8Info]
Meter = String
MeterStyle = sEInfo