[mD6Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD6Seperator]
Meter = Bar
MeterStyle = sSeperator

; Meter Dummy
[mD6Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD6E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD6E1Info]
Meter = String
MeterStyle = sEInfo

; Element 2
; =========
; Meter Element Bar
[mD6E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E2Info]
Meter = String
MeterStyle = sEInfo

; Element 3
; =========
; Meter Element Bar
[mD6E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E3Info]
Meter = String
MeterStyle = sEInfo

; Element 4
; =========
; Meter Element Bar
[mD6E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E4Info]
Meter = String
MeterStyle = sEInfo

; Element 5
; =========
; Meter Element Bar
[mD6E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E5Info]
Meter = String
MeterStyle = sEInfo

; Element 6
; =========
; Meter Element Bar
[mD6E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E6Info]
Meter = String
MeterStyle = sEInfo

; Element 7
; =========
; Meter Element Bar
[mD6E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E7Info]
Meter = String
MeterStyle = sEInfo

; Element 8
; =========
; Meter Element Bar
[mD6E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD6E8Info]
Meter = String
MeterStyle = sEInfo