[mD7Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD7Seperator]
Meter = Bar
MeterStyle = sSeperator

; Meter Dummy
[mD7Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD7E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD7E1Info]
Meter = String
MeterStyle = sEInfo

; Element 2
; =========
; Meter Element Bar
[mD7E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E2Info]
Meter = String
MeterStyle = sEInfo

; Element 3
; =========
; Meter Element Bar
[mD7E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E3Info]
Meter = String
MeterStyle = sEInfo

; Element 4
; =========
; Meter Element Bar
[mD7E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E4Info]
Meter = String
MeterStyle = sEInfo

; Element 5
; =========
; Meter Element Bar
[mD7E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E5Info]
Meter = String
MeterStyle = sEInfo

; Element 6
; =========
; Meter Element Bar
[mD7E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E6Info]
Meter = String
MeterStyle = sEInfo

; Element 7
; =========
; Meter Element Bar
[mD7E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E7Info]
Meter = String
MeterStyle = sEInfo

; Element 8
; =========
; Meter Element Bar
[mD7E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD7E8Info]
Meter = String
MeterStyle = sEInfo