[mD8Date]
Meter = String
MeterStyle = sDateDefault

; Background
; ==================================================
; Meter Background Top Left
[mD8Seperator]
Meter = Image
MeterStyle = sSeperator

; Meter Dummy
[mD8Dummy]
Meter = Image
MeterStyle = sDummy

; Element 1
; =========
; Meter Element Bar
[mD8E1Bar]
Meter = Image
MeterStyle = sEBar
Y = (0 + 4)R

; Meter Element Info
[mD8E1Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 2
; =========
; Meter Element Bar
[mD8E2Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E2Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 3
; =========
; Meter Element Bar
[mD8E3Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E3Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 4
; =========
; Meter Element Bar
[mD8E4Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E4Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 5
; =========
; Meter Element Bar
[mD8E5Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E5Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 6
; =========
; Meter Element Bar
[mD8E6Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E6Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 7
; =========
; Meter Element Bar
[mD8E7Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E7Info]
Meter = String
MeterStyle = sEInfoDefault

; Element 8
; =========
; Meter Element Bar
[mD8E8Bar]
Meter = Image
MeterStyle = sEBar

; Meter Element Info
[mD8E8Info]
Meter = String
MeterStyle = sEInfoDefault