[yAtomicNumber]
X = 0r
Y = 0r
Padding = 4,4,0,0
FontColor = 000000
FontSize = 11
AntiAlias = 1
UpdateDivider = -1
Text = "."

[ySymbol]
X = 0r
Y = 0R
Padding = 4,3,0,0
FontColor = 000000
FontSize = 14
StringStyle = Bold
AntiAlias = 1
UpdateDivider = -1
Text = "."

[yName]
X = 0r
Y = 0R
Padding = 4,3,0,0
FontColor = 000000
FontSize = 7
AntiAlias = 1
UpdateDivider = -1
Text = "."

[yAtomicMass]
X = 0r
Y = 0R
Padding = 4,2,0,1
FontColor = 000000
FontSize = 7
AntiAlias = 1
UpdateDivider = -1
Text = "."