[yGroupDefault]
SolidColor = DDDDDD
X = 0r
Y = (0 + #ElementSpacing#)R
W = #ElementSize#
H = #ElementSize#
UpdateDivider = -1

[yGroupAlkaliMetals]
SolidColor = FFAA00

[yGroupAlkaliEarthMetals]
SolidColor = F3F300

[yGroupLanthanoids]
SolidColor = FFAA88

[yGroupActinoids]
SolidColor = DDAACC

[yGroupTransitionMetals]
SolidColor = DD9999

[yGroupPostTransitionMetals]
SolidColor = 99BBAA

[yGroupMetalloids]
SolidColor = 55CC88

[yGroupNonMetals]
SolidColor = 00EE00

[yGroupHalogen]
SolidColor = 00DDBB

[yGroupNobleGases]
SolidColor = 88AAFF

[yGroupDummy]
SolidColor = 00000001
W = (#ElementSize# - 1)
H = (#ElementSize# - 1)