[yMG]
Y = 0
W = 0
H = 0
UpdateDivider = -1

[yMG02]
X = (1 * (#ElementSize# + #ElementSpacing#))

[yMG03]
X = (2 * (#ElementSize# + #ElementSpacing#))

[yMG04]
X = (3 * (#ElementSize# + #ElementSpacing#))

[yMG05]
X = (4 * (#ElementSize# + #ElementSpacing#))

[yMG06]
X = (5 * (#ElementSize# + #ElementSpacing#))

[yMG07]
X = (6 * (#ElementSize# + #ElementSpacing#))

[yMG08]
X = (7 * (#ElementSize# + #ElementSpacing#))

[yMG09]
X = (8 * (#ElementSize# + #ElementSpacing#))

[yMG10]
X = (9 * (#ElementSize# + #ElementSpacing#))

[yMG11]
X = (10 * (#ElementSize# + #ElementSpacing#))

[yMG12]
X = (11 * (#ElementSize# + #ElementSpacing#))

[yMG13]
X = (12 * (#ElementSize# + #ElementSpacing#))

[yMG14]
X = (13 * (#ElementSize# + #ElementSpacing#))

[yMG15]
X = (14 * (#ElementSize# + #ElementSpacing#))

[yMG16]
X = (15 * (#ElementSize# + #ElementSpacing#))

[yMG17]
X = (16 * (#ElementSize# + #ElementSpacing#))

[yMG18]
X = (17 * (#ElementSize# + #ElementSpacing#))
