name: Outdoor Simulator

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: test
      run: |
        luarocks install busted
        busted -o utfTerminal OutdoorSimulator
